Repository sermant-io/Sermant, pull requests merged in 2021-11, with the labels that each got.

#85 【BUG】解决CPU占用率过高问题
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/lubanops/integration/transport/netty/client/NettyClient.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/lubanops/integration/transport/netty/client/Sender.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/lubanops/integration/transport/netty/client/ThreadPools.java
Labels: bug

#87 【CI】添加actions配置，开启github自动构建功能
  .github/workflows/maven.yml
Labels: enhancement

#88 【功能】抽出抛出业务异常入口
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/agent/enhancer/AbstractAroundEnhancer.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/agent/enhancer/InstanceMethodEnhancer.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/agent/enhancer/StaticMethodEnhancer.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/exception/BizException.java
  javamesh-samples/javamesh-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/DubboInterceptor.java
  javamesh-samples/javamesh-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/exception/FlowControlException.java
Labels: enhancement

#102 log同步输出到控制台
  javamesh-agentcore/javamesh-agentcore-premain/src/main/java/com/huawei/apm/premain/lubanops/log/CollectorLogFactory.java
Labels: enhancement

#107 log同步输出到控制台
  javamesh-agentcore/javamesh-agentcore-premain/src/main/java/com/huawei/apm/premain/lubanops/log/CollectorLogFactory.java
Labels: enhancement

#110 server-monitor-plugin模块更名为server-monitor-service
  javamesh-samples/javamesh-server-monitor/pom.xml
  javamesh-samples/javamesh-server-monitor/server-monitor-service/pom.xml
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/collector/CpuMetricCollector.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/collector/DiskMetricCollector.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/collector/IbmJvmMetricCollector.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/collector/MemoryMetricCollector.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/collector/NetworkMetricCollector.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/command/Command.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/command/CommandExecutor.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/command/CommonMonitorCommand.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/command/CpuCommand.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/command/DiskCommand.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/command/MemoryCommand.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/command/MonitorCommand.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/command/NetworkCommand.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/common/CalculateUtil.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/common/CheckIBMParameter.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/common/Constant.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/common/Consumer.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/common/Function.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/common/Supplier.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/service/CollectTask.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/service/IbmJvmCollectService.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/service/OracleJvmCollectService.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/service/ServerMonitorService.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/resources/META-INF/services/com.huawei.apm.core.plugin.service.PluginService
Labels: enhancement

#113 【bug修复】修复插件配置文件不存在时获取到的插件配置对象为空的问题
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/exception/IllegalConfigException.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/plugin/config/PluginConfigManager.java
  javamesh-samples/javamesh-example/demo-application/pom.xml
  javamesh-samples/javamesh-example/demo-plugin/src/main/java/com/huawei/example/demo/interceptor/DemoConfigInterceptor.java
  javamesh-samples/javamesh-example/demo-service/src/main/java/com/huawei/example/demo/service/DemoComplexServiceImpl.java
  javamesh-samples/javamesh-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/core/config/KafkaConnectBySslSwitch.java
  javamesh-samples/javamesh-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/core/util/PluginConfigUtil.java
  javamesh-samples/javamesh-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/core/util/ZookeeperConnectionEnum.java
  javamesh-samples/javamesh-flowrecord/flowrecord-plugin/src/main/java/com/huawei/flowrecord/utils/PluginConfigUtil.java
  javamesh-samples/javamesh-route/label-plugin/src/main/java/com/huawei/route/label/LabelInitServiceImpl.java
  javamesh-samples/javamesh-route/report-plugin/src/main/java/com/huawei/route/report/ReporterPluginInitServiceImpl.java
Labels: bug

#111 服务监控添加注册信息
  javamesh-backend/src/main/java/com/huawei/apm/backend/common/conf/KafkaConf.java
  javamesh-backend/src/main/java/com/huawei/apm/backend/server/ServerHandler.java
  javamesh-backend/src/main/proto/Message.proto
  javamesh-backend/src/main/resources/application.properties
  javamesh-samples/javamesh-server-monitor/config/config.yaml
  javamesh-samples/javamesh-server-monitor/metric-server/src/main/java/com/huawei/javamesh/metricserver/controller/AgentRegistrationController.java
  javamesh-samples/javamesh-server-monitor/metric-server/src/main/java/com/huawei/javamesh/metricserver/dto/register/AgentRegistrationDTO.java
  javamesh-samples/javamesh-server-monitor/metric-server/src/main/java/com/huawei/javamesh/metricserver/dto/register/NetworkAddressDTO.java
  javamesh-samples/javamesh-server-monitor/metric-server/src/main/java/com/huawei/javamesh/metricserver/kafka/AgentRegistrationKafkaReceiver.java
  javamesh-samples/javamesh-server-monitor/metric-server/src/main/java/com/huawei/javamesh/metricserver/service/AgentRegistrationService.java
  javamesh-samples/javamesh-server-monitor/protocol/src/main/proto/AgentRegistration.proto
  javamesh-samples/javamesh-server-monitor/server-monitor-service/pom.xml
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/collecttask/CollectTask.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/collecttask/IbmJvmMetricProvider.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/collecttask/MetricProvider.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/collecttask/OpenJvmMetricProvider.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/collecttask/ServerMonitorMetricProvider.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/config/ServerMonitorConfig.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/config/ServiceConfig.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/service/CollectTask.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/service/IbmJvmCollectService.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/service/MonitorService.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/service/ServerMonitorService.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/resources/META-INF/services/com.huawei.apm.core.plugin.config.PluginConfig
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/resources/META-INF/services/com.huawei.apm.core.plugin.service.PluginService
Labels: enhancement

#115 框架日志采用logback统一
  javamesh-agentcore/javamesh-agentcore-core/pom.xml
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/AgentCoreEntrance.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/common/PathIndexer.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/log/LogBackInit.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/resources/config/logback.xml
  javamesh-agentcore/javamesh-agentcore-premain/src/main/java/com/huawei/apm/premain/common/BootArgsBuilder.java
  javamesh-agentcore/javamesh-agentcore-premain/src/main/java/com/huawei/apm/premain/common/PathDeclarer.java
Labels: enhancement

#117 解决录制插件录制流量入参错误的问题
  javamesh-samples/javamesh-flowrecord/flowrecord-plugin/src/main/java/com/huawei/flowrecord/domain/HttpRequestEntity.java
  javamesh-samples/javamesh-flowrecord/flowrecord-plugin/src/main/java/com/huawei/flowrecord/plugins/http/v4/HttpServerInterceptor.java
Labels: bug

#121 启动后luban报错问题修改
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/lubanops/core/monitor/MonitorReportServiceImpl.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/lubanops/core/trace/TraceReportServiceImpl.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/proto/Message.proto
  javamesh-agentcore/javamesh-agentcore-premain/src/main/resources/config/bootstrap.properties
  javamesh-backend/pom.xml
  javamesh-backend/src/main/java/com/huawei/apm/backend/common/conf/KafkaConf.java
  javamesh-backend/src/main/java/com/huawei/apm/backend/entity/Address.java
  javamesh-backend/src/main/java/com/huawei/apm/backend/entity/AddressScope.java
  javamesh-backend/src/main/java/com/huawei/apm/backend/entity/AddressType.java
  javamesh-backend/src/main/java/com/huawei/apm/backend/entity/HeartBeatResult.java
  javamesh-backend/src/main/java/com/huawei/apm/backend/entity/MonitorItem.java
  javamesh-backend/src/main/java/com/huawei/apm/backend/entity/Protocol.java
  javamesh-backend/src/main/java/com/huawei/apm/backend/entity/RegisterResult.java
  javamesh-backend/src/main/java/com/huawei/apm/backend/entity/Result.java
  javamesh-backend/src/main/java/com/huawei/apm/backend/server/HttpServer.java
  javamesh-backend/src/main/java/com/huawei/apm/backend/server/ServerHandler.java
  javamesh-backend/src/main/java/com/huawei/apm/backend/util/RandomUtil.java
  javamesh-backend/src/main/proto/Message.proto
  javamesh-backend/src/main/resources/application.properties
  pom.xml
Labels: bug

#119 DRUID监控 插件端
  javamesh-backend/src/main/java/com/huawei/apm/backend/common/conf/KafkaConf.java
  javamesh-backend/src/main/java/com/huawei/apm/backend/server/ServerHandler.java
  javamesh-backend/src/main/proto/Message.proto
  javamesh-backend/src/main/resources/application.properties
  javamesh-samples/javamesh-server-monitor/config/config.yaml
  javamesh-samples/javamesh-server-monitor/connection-pool-collect-plugin/pom.xml
  javamesh-samples/javamesh-server-monitor/connection-pool-collect-plugin/src/main/java/com/huawei/javamesh/sample/connection/pool/collect/collector/DruidMetricCollector.java
  javamesh-samples/javamesh-server-monitor/connection-pool-collect-plugin/src/main/java/com/huawei/javamesh/sample/connection/pool/collect/collector/DruidMetricProvider.java
  javamesh-samples/javamesh-server-monitor/connection-pool-collect-plugin/src/main/java/com/huawei/javamesh/sample/connection/pool/collect/config/DruidMonitorConfig.java
  javamesh-samples/javamesh-server-monitor/connection-pool-collect-plugin/src/main/java/com/huawei/javamesh/sample/connection/pool/collect/definition/DruidDataSourceStatManagerDefinition.java
  javamesh-samples/javamesh-server-monitor/connection-pool-collect-plugin/src/main/java/com/huawei/javamesh/sample/connection/pool/collect/interceptor/AddDataSourceInterceptor.java
  javamesh-samples/javamesh-server-monitor/connection-pool-collect-plugin/src/main/java/com/huawei/javamesh/sample/connection/pool/collect/interceptor/RemoveDataSourceInterceptor.java
  javamesh-samples/javamesh-server-monitor/connection-pool-collect-plugin/src/main/java/com/huawei/javamesh/sample/connection/pool/collect/service/DruidMonitorService.java
  javamesh-samples/javamesh-server-monitor/connection-pool-collect-plugin/src/main/resources/META-INF/services/com.huawei.apm.core.agent.definition.EnhanceDefinition
  javamesh-samples/javamesh-server-monitor/connection-pool-collect-plugin/src/main/resources/META-INF/services/com.huawei.apm.core.plugin.config.PluginConfig
  javamesh-samples/javamesh-server-monitor/metric-server/src/main/java/com/huawei/javamesh/metricserver/config/KafkaConfig.java
  javamesh-samples/javamesh-server-monitor/monitor-common/pom.xml
  javamesh-samples/javamesh-server-monitor/monitor-common/src/main/java/com/huawei/javamesh/sample/monitor/common/collect/CollectTask.java
  javamesh-samples/javamesh-server-monitor/monitor-common/src/main/java/com/huawei/javamesh/sample/monitor/common/collect/MetricProvider.java
  javamesh-samples/javamesh-server-monitor/monitor-common/src/main/java/com/huawei/javamesh/sample/monitor/common/config/ServiceConfig.java
  javamesh-samples/javamesh-server-monitor/monitor-common/src/main/resources/META-INF/services/com.huawei.apm.core.plugin.config.PluginConfig
  javamesh-samples/javamesh-server-monitor/pom.xml
  javamesh-samples/javamesh-server-monitor/protocol/src/main/proto/ConnectionPoolMonitor.proto
  javamesh-samples/javamesh-server-monitor/server-monitor-service/pom.xml
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/config/ServiceConfig.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/provider/IbmJvmMetricProvider.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/provider/OpenJvmMetricProvider.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/provider/ServerMonitorMetricProvider.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/service/MonitorService.java
  javamesh-samples/javamesh-server-monitor/server-monitor-service/src/main/resources/META-INF/services/com.huawei.apm.core.plugin.config.PluginConfig
Labels: enhancement

#124 【新功能】README目录规范
  docs/README.md
  docs/dev-guide/dev_plugin.md
  docs/dev-guide/dev_sample.md
  docs/dev-guide/service_dynamicconfig.md
  docs/dev-guide/service_heartbeat.md
  docs/dev-guide/service_send.md
  docs/dev-guide/service_template.md
  docs/user-guide/agentcore.md
  docs/user-guide/backend.md
  docs/user-guide/entrance.md
  docs/user-guide/flowcontrol/document.md
  docs/user-guide/flowrecord/document.md
  docs/user-guide/hercules/document.md
  docs/user-guide/online-stresstest/document.md
  docs/user-guide/route/document.md
  docs/user-guide/server-monitor/document.md
  docs/user-guide/template/document.md
  docs/user-guide/threadlocal/document.md
  javamesh-backend/README.md
  javamesh-samples/javamesh-flowcontrol/README.md
  javamesh-samples/javamesh-flowrecord/README.md
  javamesh-samples/javamesh-hercules/README.md
  javamesh-samples/javamesh-route/README.md
  javamesh-samples/javamesh-server-monitor/README.md
  javamesh-samples/javamesh-threadlocal/README.md
Labels: enhancement

#131 README添加聊天室入口和构建出包状态
  README.md
Labels: enhancement

#129 【新功能】统一配置系统整改、添加backend打包流程、移除luban旧日志系统、修复插件类加载器相关问题
  docs/README.md
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/AgentCoreEntrance.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/agent/transformer/BootstrapTransformer.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/agent/transformer/DelegateTransformer.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/agent/transformer/MethodInterceptorCollector.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/config/ConfigManager.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/config/strategy/LoadPropertiesStrategy.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/config/strategy/LoadYamlStrategy.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/config/utils/ConfigFieldUtil.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/config/utils/ConfigValueUtil.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/log/LogBackInit.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/plugin/classloader/PluginClassLoader.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/plugin/config/PluginConfigManager.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/plugin/service/PluginServiceManager.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/service/ServiceManager.java
  javamesh-agentcore/javamesh-agentcore-premain/src/main/java/com/huawei/apm/premain/AgentPremain.java
  javamesh-agentcore/javamesh-agentcore-premain/src/main/java/com/huawei/apm/premain/common/BootArgsBuilder.java
  javamesh-agentcore/javamesh-agentcore-premain/src/main/java/com/huawei/apm/premain/lubanops/log/CollectorLogFactory.java
  javamesh-agentcore/javamesh-agentcore-premain/src/main/java/com/huawei/apm/premain/lubanops/log/JdkLoggerAdapter.java
  javamesh-samples/javamesh-example/demo-plugin/src/main/java/com/huawei/example/demo/interceptor/DemoServiceInterceptor.java
  javamesh-samples/javamesh-example/demo-plugin/src/main/java/com/huawei/example/demo/interceptor/DemoTraceInterceptor.java
  javamesh-samples/javamesh-example/demo-plugin/src/main/java/com/huawei/example/demo/service/DemoSimpleService.java
  javamesh-samples/javamesh-example/demo-service/src/main/java/com/huawei/example/demo/service/DemoComplexServiceImpl.java
  pom.xml
Labels: enhancement

#139 backend添加查询插件心跳数据接口，数据类型判断逻辑修改
  javamesh-backend/pom.xml
  javamesh-backend/src/main/java/com/huawei/apm/backend/common/conf/KafkaConf.java
  javamesh-backend/src/main/java/com/huawei/apm/backend/common/constants/ProducerConstants.java
  javamesh-backend/src/main/java/com/huawei/apm/backend/entity/AgentInfo.java
  javamesh-backend/src/main/java/com/huawei/apm/backend/kafka/KafkaConsumerManager.java
  javamesh-backend/src/main/java/com/huawei/apm/backend/kafka/KafkaProducerManager.java
  javamesh-backend/src/main/java/com/huawei/apm/backend/server/HttpServer.java
  javamesh-backend/src/main/java/com/huawei/apm/backend/server/NettyServer.java
  javamesh-backend/src/main/java/com/huawei/apm/backend/server/ServerHandler.java
  javamesh-backend/src/main/java/com/huawei/apm/backend/service/SendAgentMonitor.java
  javamesh-backend/src/main/java/com/huawei/apm/backend/service/SendAgentRegistration.java
  javamesh-backend/src/main/java/com/huawei/apm/backend/service/SendAgentSpanEvent.java
  javamesh-backend/src/main/java/com/huawei/apm/backend/service/SendDruidMonitor.java
  javamesh-backend/src/main/java/com/huawei/apm/backend/service/SendFlowControl.java
  javamesh-backend/src/main/java/com/huawei/apm/backend/service/SendFlowRecord.java
  javamesh-backend/src/main/java/com/huawei/apm/backend/service/SendHeartbeat.java
  javamesh-backend/src/main/java/com/huawei/apm/backend/service/SendIbmJvmMonitor.java
  javamesh-backend/src/main/java/com/huawei/apm/backend/service/SendLog.java
  javamesh-backend/src/main/java/com/huawei/apm/backend/service/SendOracleJvmMonitor.java
  javamesh-backend/src/main/java/com/huawei/apm/backend/service/SendServerMonitor.java
  javamesh-backend/src/main/java/com/huawei/apm/backend/service/SendService.java
  javamesh-backend/src/main/java/com/huawei/apm/backend/service/SendServiceManager.java
  javamesh-backend/src/main/resources/application.properties
  javamesh-backend/src/test/java/com/huawei/apm/backend/NettyServerTest.java
Labels: enhancement

#147 【新功能/bug修复】心跳系统整改、项目依赖整理、添加内禀版本设计、修复logback初始化异常等
  docs/README.md
  docs/dev-guide/dev_plugin.md
  docs/dev-guide/dev_sample.md
  docs/user-guide/agentcore.md
  javamesh-agentcore/javamesh-agentcore-core/pom.xml
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/AgentCoreEntrance.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/common/BootArgsIndexer.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/common/CommonConstant.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/common/LoggerFactory.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/config/ConfigManager.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/config/utils/ConfigValueUtil.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/exception/DupConfIndexException.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/exception/SchemaException.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/lubanops/core/BootStrapImpl.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/plugin/PluginManager.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/plugin/common/PluginConstant.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/plugin/config/PluginConfigManager.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/service/heartbeat/ExtInfoProvider.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/service/heartbeat/HeartbeatConfig.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/service/heartbeat/HeartbeatInterval.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/service/heartbeat/HeartbeatService.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/service/heartbeat/HeartbeatServiceImpl.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/util/FileUtil.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/util/JarFileUtil.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/resources/META-INF/services/com.huawei.apm.core.config.common.BaseConfig
  javamesh-agentcore/javamesh-agentcore-core/src/main/resources/config/config.properties
  javamesh-agentcore/javamesh-agentcore-premain/pom.xml
  javamesh-agentcore/javamesh-agentcore-premain/src/main/java/com/huawei/apm/premain/AgentPremain.java
  javamesh-agentcore/javamesh-agentcore-premain/src/main/java/com/huawei/apm/premain/common/BootArgsBuilder.java
  javamesh-agentcore/javamesh-agentcore-premain/src/main/java/com/huawei/apm/premain/common/PathDeclarer.java
  javamesh-backend/pom.xml
  javamesh-package/pom.xml
  javamesh-samples/javamesh-example/demo-application/pom.xml
  javamesh-samples/javamesh-example/demo-plugin/src/main/java/com/huawei/example/demo/service/DemoHeartBeatService.java
  javamesh-samples/javamesh-example/demo-plugin/src/main/java/com/huawei/example/demo/service/DemoSimpleService.java
  javamesh-samples/javamesh-flowrecord/flowrecord-plugin/pom.xml
  javamesh-samples/javamesh-flowrecord/flowrecord-plugin/src/main/java/com/huawei/flowrecord/FlowrecordService.java
  javamesh-samples/javamesh-flowrecord/flowrecord-plugin/src/main/resources/META-INF/services/com.huawei.apm.core.plugin.service.PluginService
  javamesh-samples/pom.xml
  pom.xml
Labels: bug, enhancement

#153 门禁配置修改，提交pr后显示门禁结果
  .github/workflows/maven.yml
Labels: enhancement
