Repository sermant-io/Sermant, pull requests merged in 2021-12, with the labels that each got.

#155 core心跳添加版本字段，查询插件信息接口修改
  .github/workflows/maven.yml
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/javamesh/core/lubanops/core/transfer/dto/heartbeat/HeartbeatMessage.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/javamesh/core/service/heartbeat/HeartbeatService.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/javamesh/core/service/heartbeat/HeartbeatServiceImpl.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/entity/AgentInfo.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/entity/PluginInfo.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/server/HttpServer.java
Labels: enhancement

#162 【新功能/bug修复】心跳服务readme，心跳功能的额外信息方法屏蔽插件名称，修复动态配置系统zk实现，遍历节点时，若节点不存在则报错的问题
  docs/dev-guide/dev_plugin_code.md
  docs/dev-guide/dev_plugin_module.md
  docs/dev-guide/service_heartbeat.md
  docs/user-guide/agentcore.md
  docs/user-guide/backend.md
  docs/user-guide/entrance.md
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/javamesh/core/plugin/PluginManager.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/javamesh/core/service/dynamicconfig/zookeeper/ZookeeperDynamicConfigurationService.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/javamesh/core/service/heartbeat/HeartbeatService.java
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/javamesh/core/service/heartbeat/HeartbeatServiceImpl.java
  javamesh-plugins/javamesh-example/demo-plugin/pom.xml
  javamesh-plugins/javamesh-example/demo-plugin/src/main/java/com/huawei/example/demo/service/DemoHeartBeatService.java
  javamesh-plugins/javamesh-example/demo-service/pom.xml
  javamesh-plugins/javamesh-example/pom.xml
  javamesh-plugins/javamesh-flowcontrol/flowcontrol-plugin/pom.xml
  javamesh-plugins/javamesh-flowcontrol/pom.xml
  javamesh-plugins/javamesh-flowrecord/flowrecord-plugin/pom.xml
  javamesh-plugins/javamesh-flowrecord/pom.xml
  javamesh-plugins/javamesh-online-stresstest/online-stresstest-plugin/pom.xml
  javamesh-plugins/javamesh-online-stresstest/pom.xml
  javamesh-plugins/javamesh-route/gray-dubbo-2.7.x-plugin/pom.xml
  javamesh-plugins/javamesh-route/gray-dubbo-2.7.x-service/pom.xml
  javamesh-plugins/javamesh-route/gray-feign-http-9.x-plugin/pom.xml
  javamesh-plugins/javamesh-route/gray-feign-http-9.x-service/pom.xml
  javamesh-plugins/javamesh-route/pom.xml
  javamesh-plugins/javamesh-route/route-common/pom.xml
  javamesh-plugins/javamesh-server-monitor/connection-pool-collect-plugin/pom.xml
  javamesh-plugins/javamesh-server-monitor/databasepeer-parse-service/pom.xml
  javamesh-plugins/javamesh-server-monitor/pom.xml
  javamesh-plugins/javamesh-server-monitor/server-monitor-service/pom.xml
  javamesh-plugins/javamesh-threadlocal/pom.xml
  javamesh-plugins/javamesh-threadlocal/threadlocal-plugin/pom.xml
  javamesh-plugins/pom.xml
Labels: bug, documentation, enhancement

#165 update readme.md by adding related projects.
  README.md
Labels: documentation

#197 Delete reviewer and reason in pr template
  .github/pull_request_template.md
Labels: documentation

#200 backend module add Huawei Copyright
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/NettyServerApplication.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/common/conf/KafkaConf.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/common/exception/ErrorMsgParser.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/common/exception/KafkaTopicException.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/common/handler/BaseHandler.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/common/util/GzipUtils.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/entity/Address.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/entity/AddressScope.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/entity/AddressType.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/entity/AgentInfo.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/entity/HeartBeatResult.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/entity/MonitorItem.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/entity/PluginInfo.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/entity/Protocol.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/entity/RegisterResult.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/entity/Result.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/kafka/KafkaConsumerManager.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/kafka/KafkaProducerManager.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/server/HttpServer.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/server/NettyServer.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/server/ServerHandler.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/SendAgentMonitor.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/SendAgentRegistration.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/SendAgentSpanEvent.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/SendDruidMonitor.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/SendFlowControl.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/SendFlowRecord.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/SendHeartbeat.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/SendIbmJvmMonitor.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/SendLog.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/SendOracleJvmMonitor.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/SendServerMonitor.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/SendService.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/SendServiceManager.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/util/RandomUtil.java
Labels: documentation

#207 删除backend和flowrecord插件无用的代码和文件
  javamesh-backend/.gitignore
  javamesh-plugins/javamesh-flowrecord/flowrecord-plugin/src/main/java/com/huawei/flowrecord/plugins/dubbo/AliDubboInterceptor.java
  javamesh-plugins/javamesh-flowrecord/flowrecord-plugin/src/main/java/com/huawei/flowrecord/plugins/dubbo/DubboInterceptor.java
  javamesh-plugins/javamesh-flowrecord/flowrecord-plugin/src/main/java/com/huawei/flowrecord/utils/ProducerConfig.java
  javamesh-plugins/javamesh-flowrecord/flowrecord-plugin/src/main/java/com/huawei/flowrecord/utils/StringUtil.java
  javamesh-plugins/javamesh-flowrecord/flowrecord-plugin/src/main/java/com/huawei/flowrecord/utils/base64Util.java
  javamesh-plugins/javamesh-flowrecord/flowrecord-replay/.github/ISSUE_TEMPLATE/bug.md
  javamesh-plugins/javamesh-flowrecord/flowrecord-replay/ISSUE_TEMPLATE/feature.md
  javamesh-plugins/javamesh-flowrecord/flowrecord-replay/ISSUE_TEMPLATE/question.md
  javamesh-plugins/javamesh-flowrecord/flowrecord-replay/PULL_REQUEST_TEMPLATE.md
  javamesh-plugins/javamesh-flowrecord/flowrecord-replay/checkstyle_ruleset_minimal.xml
Labels: bug

#221 【新功能】为二进制包添加LICENSE和NOTICE
  .github/workflows/maven.yml
  LICENSE
  NOTICE
  javamesh-package/bin/append.bat
  javamesh-package/bin/append.sh
  javamesh-package/pom.xml
  javamesh-package/resources/META-INF/LICENSE
  javamesh-package/resources/META-INF/NOTICE
  javamesh-package/resources/third-party-license.ftl
  javamesh-plugins/javamesh-flowcontrol/flowcontrol-plugin/pom.xml
  javamesh-plugins/javamesh-flowrecord/flowrecord-plugin/pom.xml
  javamesh-plugins/javamesh-server-monitor/connection-pool-collect-plugin/pom.xml
  javamesh-plugins/javamesh-server-monitor/databasepeer-parse-service/pom.xml
  javamesh-plugins/javamesh-server-monitor/server-monitor-service/pom.xml
  pom.xml
Labels: enhancement

#226 【log】处理统一配置系统配置类重复加载误提示
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/javamesh/core/config/ConfigManager.java
Labels: enhancement

#227 【doc】添加第三方版权说明手册
  docs/README.md
  docs/dev-guide/third_party_copyright.md
Labels: documentation

#225 【enhancement】backend添加修改配置服务，添加logback日志
  javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/javamesh/core/lubanops/core/master/RegionMasterService.java
  javamesh-backend/pom.xml
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/dynamicconfig/Config.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/dynamicconfig/DynamicConfigurationFactoryServiceImpl.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/dynamicconfig/kie/KieDynamicConfigurationServiceImpl.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/dynamicconfig/kie/client/AbstractClient.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/dynamicconfig/kie/client/Client.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/dynamicconfig/kie/client/ClientUrlManager.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/dynamicconfig/kie/client/http/DefaultHttpClient.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/dynamicconfig/kie/client/http/HttpClient.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/dynamicconfig/kie/client/http/HttpResult.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/dynamicconfig/kie/client/kie/KieClient.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/dynamicconfig/kie/client/kie/KieConfigEntity.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/dynamicconfig/kie/client/kie/KieListenerWrapper.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/dynamicconfig/kie/client/kie/KieRequest.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/dynamicconfig/kie/client/kie/KieResponse.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/dynamicconfig/kie/client/kie/KieSubscriber.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/dynamicconfig/kie/client/kie/ResultHandler.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/dynamicconfig/kie/constants/KieConstants.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/dynamicconfig/kie/listener/KvDataHolder.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/dynamicconfig/kie/listener/SubscriberManager.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/dynamicconfig/kie/selector/SelectStrategy.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/dynamicconfig/kie/selector/Selector.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/dynamicconfig/kie/selector/url/UrlSelector.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/dynamicconfig/nop/NopDynamicConfigurationService.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/dynamicconfig/service/ConfigChangeType.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/dynamicconfig/service/ConfigChangedEvent.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/dynamicconfig/service/ConfigurationListener.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/dynamicconfig/service/DynamicConfigType.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/dynamicconfig/service/DynamicConfigurationFactoryService.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/dynamicconfig/service/DynamicConfigurationService.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/dynamicconfig/utils/LabelGroupUtils.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/service/dynamicconfig/zookeeper/ZookeeperDynamicConfigurationService.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/util/BackendThreadFactory.java
  javamesh-backend/src/main/resources/logback.xml
Labels: enhancement

#228 backend增加修改配置接口
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/entity/PublishConfigEntity.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/server/HttpServer.java
  javamesh-backend/src/main/java/com/huawei/javamesh/backend/util/BackendThreadFactory.java
Labels: enhancement

#242 错误日志和校验参数补充
  sermant-plugins/sermant-server-monitor/monitor-common/src/main/java/com/huawei/sermant/sample/monitor/common/collect/CollectTask.java
  sermant-plugins/sermant-server-monitor/monitor-common/src/main/java/com/huawei/sermant/sample/monitor/common/utils/CommonUtil.java
  sermant-plugins/sermant-server-monitor/server-monitor-service/src/main/java/com/huawei/sermant/sample/servermonitor/collector/CpuMetricCollector.java
  sermant-plugins/sermant-server-monitor/server-monitor-service/src/main/java/com/huawei/sermant/sample/servermonitor/collector/DiskMetricCollector.java
  sermant-plugins/sermant-server-monitor/server-monitor-service/src/main/java/com/huawei/sermant/sample/servermonitor/collector/NetworkMetricCollector.java
  sermant-plugins/sermant-server-monitor/server-monitor-service/src/main/java/com/huawei/sermant/sample/servermonitor/command/CommandExecutor.java
  sermant-plugins/sermant-server-monitor/server-monitor-service/src/main/java/com/huawei/sermant/sample/servermonitor/command/CommonMonitorCommand.java
  sermant-plugins/sermant-server-monitor/server-monitor-service/src/main/java/com/huawei/sermant/sample/servermonitor/provider/OpenJvmMetricProvider.java
Labels: bug

#246 【Fix】修复复杂插件服务start方法中使用的第三方依赖的slf4j api错误的问题
  docs/dev-guide/dev_plugin_code.md
  docs/dev-guide/dev_plugin_module.md
  pom.xml
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/plugin/classloader/PluginClassLoader.java
  sermant-plugins/sermant-example/demo-service/pom.xml
  sermant-plugins/sermant-example/demo-service/src/main/java/com/huawei/example/demo/service/DemoComplexServiceImpl.java
Labels: bug

#254 【doc】补充contributing和code_of_conduct文件
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  docs/binary-docs/contributor_definition.png
Labels: documentation

#251 backend添加展示agent插件界面
  pom.xml
  sermant-backend/pom.xml
  sermant-backend/src/main/java/com/huawei/sermant/backend/common/conf/KafkaConf.java
  sermant-backend/src/main/java/com/huawei/sermant/backend/common/conf/WebConfig.java
  sermant-backend/src/main/java/com/huawei/sermant/backend/entity/AgentInfo.java
  sermant-backend/src/main/java/com/huawei/sermant/backend/entity/HeartbeatEntity.java
  sermant-backend/src/main/java/com/huawei/sermant/backend/kafka/KafkaConsumerManager.java
  sermant-backend/src/main/java/com/huawei/sermant/backend/server/HttpServer.java
  sermant-backend/src/main/java/com/huawei/sermant/backend/util/DateUtil.java
  sermant-backend/src/main/resources/application.properties
  sermant-backend/src/main/webapp/frontend/.babelrc
  sermant-backend/src/main/webapp/frontend/.editorconfig
  sermant-backend/src/main/webapp/frontend/.eslintignore
  sermant-backend/src/main/webapp/frontend/.eslintrc.js
  sermant-backend/src/main/webapp/frontend/.postcssrc.js
  sermant-backend/src/main/webapp/frontend/README.md
  sermant-backend/src/main/webapp/frontend/build/build.js
  sermant-backend/src/main/webapp/frontend/build/check-versions.js
  sermant-backend/src/main/webapp/frontend/build/logo.png
  sermant-backend/src/main/webapp/frontend/build/utils.js
  sermant-backend/src/main/webapp/frontend/build/vue-loader.conf.js
  sermant-backend/src/main/webapp/frontend/build/webpack.base.conf.js
  sermant-backend/src/main/webapp/frontend/build/webpack.dev.conf.js
  sermant-backend/src/main/webapp/frontend/build/webpack.prod.conf.js
  sermant-backend/src/main/webapp/frontend/config/dev.env.js
  sermant-backend/src/main/webapp/frontend/config/index.js
  sermant-backend/src/main/webapp/frontend/config/prod.env.js
  sermant-backend/src/main/webapp/frontend/config/test.env.js
  sermant-backend/src/main/webapp/frontend/dist/index.html
  sermant-backend/src/main/webapp/frontend/dist/static/css/app.css
  sermant-backend/src/main/webapp/frontend/dist/static/css/app.css.map
  sermant-backend/src/main/webapp/frontend/dist/static/js/app.js
  sermant-backend/src/main/webapp/frontend/dist/static/js/app.js.map
  sermant-backend/src/main/webapp/frontend/dist/static/js/manifest.js
  sermant-backend/src/main/webapp/frontend/dist/static/js/manifest.js.map
  sermant-backend/src/main/webapp/frontend/dist/static/js/vendor.js
  sermant-backend/src/main/webapp/frontend/dist/static/js/vendor.js.map
  sermant-backend/src/main/webapp/frontend/index.html
  sermant-backend/src/main/webapp/frontend/package-lock.json
  sermant-backend/src/main/webapp/frontend/package.json
  sermant-backend/src/main/webapp/frontend/src/App.vue
  sermant-backend/src/main/webapp/frontend/src/assets/logo.png
  sermant-backend/src/main/webapp/frontend/src/components/PluginsInfo.vue
  sermant-backend/src/main/webapp/frontend/src/main.js
  sermant-backend/src/main/webapp/frontend/src/router/index.js
  sermant-backend/src/main/webapp/frontend/static/.gitkeep
  sermant-backend/src/main/webapp/frontend/test/e2e/custom-assertions/elementCount.js
  sermant-backend/src/main/webapp/frontend/test/e2e/nightwatch.conf.js
  sermant-backend/src/main/webapp/frontend/test/e2e/runner.js
  sermant-backend/src/main/webapp/frontend/test/e2e/specs/test.js
  sermant-backend/src/main/webapp/frontend/test/unit/.eslintrc
  sermant-backend/src/main/webapp/frontend/test/unit/jest.conf.js
  sermant-backend/src/main/webapp/frontend/test/unit/setup.js
  sermant-backend/src/main/webapp/frontend/test/unit/specs/HelloWorld.spec.js
Labels: enhancement

#263 【bug】解决backned日志中文注释解析失败导致backned启动失败问题
  sermant-backend/pom.xml
Labels: bug

#268 【Doc】补充动态配置服务的开发手册
  docs/dev-guide/dev_plugin_code.md
  docs/dev-guide/service_dynamicconfig.md
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/dynamicconfig/zookeeper/ZooKeeperBufferedClient.java
Labels: documentation

#270 【perf】自动关闭issue和pr的工作流调整
  .github/workflows/stale.yml
Labels: bug

#273 【workflow】暂时将关闭issue和pr的step合并，提升处理总条数
  .github/workflows/stale.yml
Labels: bug

#272 【Doc】添加版本管理手册
  docs/README.md
  docs/dev-guide/version_manage.md
Labels: documentation

#275 【perf】更新log4j桥接包的版本
  pom.xml
Labels: enhancement

#277 【Fix】修复增强模板类的名称构建时对入参处理错误的问题
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/agent/template/BootstrapConstTemplate.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/agent/template/BootstrapInstTemplate.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/agent/template/BootstrapStaticTemplate.java
Labels: bug

#299 springcloud灰度发布对接CSE
  sermant-plugins/sermant-register-center/spring-cloud-register-service/src/main/java/com/huawei/register/service/client/ScClient.java
  sermant-plugins/sermant-register-center/spring-cloud-register-service/src/main/java/com/huawei/register/service/register/ScRegister.java
  sermant-plugins/sermant-route/config/config.yaml
  sermant-plugins/sermant-route/gray-feign-http-9.x-plugin/src/main/java/com/huawei/gray/feign/definition/ServiceInstanceListSupplierDefinition.java
  sermant-plugins/sermant-route/gray-feign-http-9.x-plugin/src/main/java/com/huawei/gray/feign/definition/register/RegistrationDefinition.java
  sermant-plugins/sermant-route/gray-feign-http-9.x-plugin/src/main/java/com/huawei/gray/feign/interceptor/RegistrationInterceptor.java
  sermant-plugins/sermant-route/gray-feign-http-9.x-plugin/src/main/java/com/huawei/gray/feign/interceptor/ServiceInstanceListSupplierInterceptor.java
  sermant-plugins/sermant-route/gray-feign-http-9.x-plugin/src/main/java/com/huawei/gray/feign/service/ServiceInstanceListSupplierService.java
  sermant-plugins/sermant-route/gray-feign-http-9.x-plugin/src/main/resources/META-INF/services/com.huawei.sermant.core.agent.definition.EnhanceDefinition
  sermant-plugins/sermant-route/gray-feign-http-9.x-service/src/main/java/com/huawei/gray/feign/service/ConfigServiceImpl.java
  sermant-plugins/sermant-route/gray-feign-http-9.x-service/src/main/java/com/huawei/gray/feign/service/DefaultHttpClientServiceImpl.java
  sermant-plugins/sermant-route/gray-feign-http-9.x-service/src/main/java/com/huawei/gray/feign/service/RegisterServiceImpl.java
  sermant-plugins/sermant-route/gray-feign-http-9.x-service/src/main/java/com/huawei/gray/feign/service/ServiceInstanceListSupplierServiceImpl.java
  sermant-plugins/sermant-route/gray-feign-http-9.x-service/src/main/resources/META-INF/services/com.huawei.sermant.core.plugin.service.PluginService
  sermant-plugins/sermant-route/route-common/src/main/java/com/huawei/route/common/gray/config/GrayConfig.java
  sermant-plugins/sermant-route/route-common/src/main/java/com/huawei/route/common/gray/constants/GrayConstant.java
Labels: enhancement
