Repository sermant-io/Sermant, pull requests merged in 2022-02, with the labels that each got.

#334 【BUG】类锁添加访问权限，拦截数组参数失效问题修改
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/plugin/agent/template/MethodKeyCreator.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/utils/ClassLoaderUtils.java
Labels: bug

#362 注册插件入门文档问题修改
  docs/QuickStart.md
  docs/binary-docs/register-application.PNG
  sermant-plugins/sermant-example/demo-register/pom.xml
  sermant-plugins/sermant-example/demo-register/resttemplate-consumer/pom.xml
  sermant-plugins/sermant-example/demo-register/resttemplate-consumer/src/main/java/com/huawei/zk/resttemplate/consumer/Configuration.java
  sermant-plugins/sermant-example/demo-register/resttemplate-consumer/src/main/java/com/huawei/zk/resttemplate/consumer/ConsumerApplication.java
  sermant-plugins/sermant-example/demo-register/resttemplate-consumer/src/main/resources/application.yml
  sermant-plugins/sermant-example/demo-register/resttemplate-provider/pom.xml
  sermant-plugins/sermant-example/demo-register/resttemplate-provider/src/main/java/com/huawei/zk/resttemplate/provider/ProviderApplication.java
  sermant-plugins/sermant-example/demo-register/resttemplate-provider/src/main/resources/application.yml
Labels: documentation

#363 [fix] 修改dubbo注册插件，灰度发布的代码规范与安全问题
  sermant-plugins/sermant-register-center/config/config.yaml
  sermant-plugins/sermant-route/gray-dubbo-2.7.x-plugin/src/main/java/com/huawei/gray/dubbo/definition/AbstractInstDefinition.java
  sermant-plugins/sermant-route/gray-dubbo-2.7.x-service/src/main/java/com/huawei/gray/dubbo/service/RegistrationServiceImpl.java
  sermant-plugins/sermant-route/gray-dubbo-2.7.x-service/src/main/java/com/huawei/gray/dubbo/strategy/type/ObjectTypeStrategy.java
  sermant-plugins/sermant-route/gray-dubbo-2.7.x-service/src/main/java/com/huawei/gray/dubbo/utils/FieldPrivilegedAction.java
  sermant-plugins/sermant-route/gray-feign-http-9.x-service/src/main/java/com/huawei/gray/feign/context/CurrentInstance.java
  sermant-plugins/sermant-route/route-common/src/main/java/com/huawei/route/common/gray/label/entity/Match.java
  sermant-plugins/sermant-route/route-common/src/main/java/com/huawei/route/common/gray/label/entity/ValueMatchDeserializer.java
Labels: enhancement

#372 【fix】流控checkstyle修改
  sermant-agentcore/sermant-agentcore-core/src/test/java/com/huawei/sermant/core/service/dynamicconfig/BaseTest.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/adapte/cse/converter/Converter.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/adapte/cse/converter/YamlConverter.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/adapte/cse/entity/CseServiceMeta.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/adapte/cse/match/RawOperator.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/adapte/cse/match/operator/CompareOperator.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/adapte/cse/resolver/AbstractResolver.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/adapte/cse/rule/CircuitBreakerRule.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/adapte/cse/rule/RetryRule.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/config/CommonConst.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/config/FlowControlConfig.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/enums/FlowFramework.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/handler/retry/AbstractRetry.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/init/FlowControlInitServiceImpl.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/AlibabaDubboInterceptor.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/ApacheDubboInterceptor.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/AlibabaDubboInvokerInterceptor.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/ApacheDubboInvokerInterceptor.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-server/src/main/java/com/huawei/flowcontrol/console/auth/AuthServiceImpl.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-server/src/main/java/com/huawei/flowcontrol/console/auth/AuthUserImpl.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-server/src/main/java/com/huawei/flowcontrol/console/config/CasConfig.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-server/src/main/java/com/huawei/flowcontrol/console/controller/LoginController.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-server/src/main/java/com/huawei/flowcontrol/console/controller/MetricController.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-server/src/main/java/com/huawei/flowcontrol/console/datasource/entity/rule/kie/exception/KieGeneralException.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-server/src/main/java/com/huawei/flowcontrol/console/util/SystemUtils.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-service/pom.xml
  sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/java/com/huawei/flowcontrol/adapte/cse/datasource/CseDataSourceManager.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/java/com/huawei/flowcontrol/adapte/cse/rule/isolate/IsolateThreadRule.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/java/com/huawei/flowcontrol/adapte/cse/rule/isolate/IsolateThreadRuleManager.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/java/com/huawei/flowcontrol/adapte/cse/rule/isolate/IsolateThreadSlot.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/java/com/huawei/flowcontrol/core/datasource/DefaultDataSourceManager.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/java/com/huawei/flowcontrol/core/datasource/zookeeper/ZookeeperDatasourceManager.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/test/java/com/huawei/flowcontrol/adapte/cse/test/BaseTest.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/test/java/com/huawei/flowcontrol/adapte/cse/test/MatchTest.java
Labels: enhancement
