Repository sermant-io/Sermant, pull requests merged in 2022-03, with the labels that each got.

#344 【feature】压测平台中http请求支持httpclient连接复用
  sermant-plugins/sermant-hercules/ngrinder/hercules-function/pom.xml
  sermant-plugins/sermant-hercules/ngrinder/hercules-function/src/main/java/com/huawei/test/configelement/config/HttpClientConfig.java
  sermant-plugins/sermant-hercules/ngrinder/hercules-function/src/main/java/com/huawei/test/configelement/service/HttpClientServiceInterface.java
  sermant-plugins/sermant-hercules/ngrinder/hercules-function/src/main/java/com/huawei/test/configelement/service/HttpDeleteWithBody.java
  sermant-plugins/sermant-hercules/ngrinder/hercules-function/src/main/java/com/huawei/test/configelement/service/impl/HttpClientService.java
Labels: enhancement

#376 【fix】Spring Cloud注册插件适配新架构
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/pom.xml
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/config/RegisterDynamicConfig.java
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/config/RegisterDynamicConfigSyncer.java
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/context/RegisterContext.java
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/declarers/ClientConfigDeclarer.java
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/declarers/DiscoveryClientConfigurationDeclarer.java
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/declarers/DiscoveryClientDeclarer.java
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/declarers/RegistrationDeclarer.java
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/declarers/ServerListDeclarer.java
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/declarers/health/ConsulHealthDeclarer.java
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/declarers/health/ConsulWatchConDeclarer.java
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/declarers/health/EurekaHealthDeclarer.java
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/declarers/health/NacosHealthDeclarer.java
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/declarers/health/ZookeeperHealthDeclarer.java
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/enhancers/DiscoveryClientConfigurationEnhancer.java
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/enhancers/DiscoveryClientEnhancer.java
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/enhancers/IClientConfigEnhancer.java
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/enhancers/health/ConsulHealthEnhancer.java
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/enhancers/health/EurekaHealthEnhancer.java
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/entity/FixedResult.java
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/entity/MicroServiceInstance.java
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/entity/SimpleInstanceInfo.java
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/handler/SingleStateCloseHandler.java
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/interceptors/ClientConfigInterceptor.java
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/interceptors/ClientConfigurationInterceptor.java
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/interceptors/DiscoveryClientInterceptor.java
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/interceptors/RegistrationInterceptor.java
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/interceptors/ServerListInterceptor.java
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/interceptors/health/ConsulHealthInterceptor.java
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/interceptors/health/ConsulWatchInterceptor.java
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/interceptors/health/EurekaHealthInterceptor.java
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/interceptors/health/NacosHealthInterceptor.java
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/interceptors/health/ZookeeperHealthInterceptor.java
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/services/RegisterCenterService.java
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/support/Comparator.java
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/support/FieldAccessAction.java
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/support/InstanceInterceptorSupport.java
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/resources/META-INF/services/com.huawei.sermant.core.agent.definition.EnhanceDefinition
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/resources/META-INF/services/com.huawei.sermant.core.plugin.agent.declarer.PluginDeclarer
  sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/test/java/com/huawei/register/context/RegisterContextTest.java
  sermant-plugins/sermant-register-center/spring-cloud-register-service/pom.xml
  sermant-plugins/sermant-register-center/spring-cloud-register-service/src/main/java/com/huawei/register/service/client/ScClient.java
  sermant-plugins/sermant-register-center/spring-cloud-register-service/src/main/java/com/huawei/register/service/impl/RegisterCenterServiceImpl.java
  sermant-plugins/sermant-register-center/spring-cloud-register-service/src/main/java/com/huawei/register/service/register/Register.java
  sermant-plugins/sermant-register-center/spring-cloud-register-service/src/main/java/com/huawei/register/service/register/RegisterManager.java
  sermant-plugins/sermant-register-center/spring-cloud-register-service/src/main/java/com/huawei/register/service/register/ScRegister.java
  sermant-plugins/sermant-register-center/spring-cloud-register-service/src/main/java/com/huawei/register/service/register/ScServer.java
  sermant-plugins/sermant-register-center/spring-cloud-register-service/src/main/java/com/huawei/register/service/register/ServicecombServiceInstance.java
  sermant-plugins/sermant-register-center/spring-cloud-register-service/src/main/java/com/huawei/register/service/utils/CommonUtils.java
  sermant-plugins/sermant-register-center/spring-cloud-register-service/src/test/java/com/huawei/register/service/client/BaseTest.java
  sermant-plugins/sermant-register-center/spring-cloud-register-service/src/test/java/com/huawei/register/service/client/ScClientTest.java
  sermant-plugins/sermant-register-center/spring-cloud-register-service/src/test/java/com/huawei/register/service/config/RegisterDynamicConfigSyncerTest.java
  sermant-plugins/sermant-register-center/spring-cloud-register-service/src/test/java/com/huawei/register/service/context/BaseTest.java
Labels: enhancement

#429 dev_plugin_module跳转链接失效修改
  docs/dev-guide/dev_plugin_module.md
Labels: documentation

#431 【fix】修复环境变量问题
  docs/user-guide/flowcontrol/flowcontrol.md
  docs/user-guide/flowcontrol/kie-configuration-document.md
  docs/user-guide/flowcontrol/zk-configuration-document.md
  docs/user-guide/register/document.md
  sermant-agentcore/sermant-agentcore-core/config/config.properties
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/config/strategy/LoadYamlStrategy.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/config/utils/ConfigValueUtil.java
  sermant-plugins/sermant-flowcontrol/config/config.yaml
Labels: enhancement

#426 【feature】修改插件开发手册，修改demo示例
  docs/dev-guide/dev_plugin_code.md
  docs/dev-guide/dev_plugin_module.md
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/tracing/common/TracingHeader.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/tracing/common/TracingRequest.java
  sermant-plugins/sermant-example/demo-application/src/main/java/com/huawei/example/demo/service/DemoTraceService.java
  sermant-plugins/sermant-example/demo-plugin/src/main/java/com/huawei/example/demo/declarer/DemoTraceDeclarer.java
  sermant-plugins/sermant-example/demo-plugin/src/main/java/com/huawei/example/demo/interceptor/DemoTraceConsumerInterceptor.java
  sermant-plugins/sermant-example/demo-plugin/src/main/java/com/huawei/example/demo/interceptor/DemoTraceProviderInterceptor.java
  sermant-plugins/sermant-example/demo-plugin/src/main/java/com/huawei/example/demo/interceptor/DemoTraceReceiveInterceptor.java
  sermant-plugins/sermant-example/demo-plugin/src/main/java/com/huawei/example/demo/interceptor/DemoTraceSendInterceptor.java
Labels: enhancement

#444 更改tomcat版本为9.0.43
  sermant-backend/pom.xml
Labels: enhancement

#451 【fix】增加流控FAQ文档，优化流控文档
  docs/user-guide/flowcontrol/FAQ.md
  docs/user-guide/flowcontrol/flowcontrol.md
Labels: document

#449 【fix】修复springcloud 3.x zookeeper单注册无法调用的问题
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/pom.xml
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/declarers/cloud3/x/ZookeeperInstanceSupplierDeclarer.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/entity/DiscoveryServiceInstance.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/interceptors/DiscoveryClientInterceptor.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/interceptors/cloud3/x/ZookeeperInstanceSupplierInterceptor.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/support/InstanceInterceptorSupport.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/resources/META-INF/services/com.huawei.sermant.core.plugin.agent.declarer.PluginDeclarer
Labels: enhancement

#454 【doc】增加注册插件FAQ
  docs/binary-docs/registry-faq-1.png
  docs/binary-docs/registry-faq-2.png
  docs/binary-docs/registry-faq-3.png
  docs/binary-docs/registry-faq-4.png
  docs/binary-docs/registry-faq-5.png
  docs/binary-docs/registry-faq-6.png
  docs/user-guide/registry/FAQ.md
  docs/user-guide/registry/document.md
Labels: document

#456 【feature】增加dubbo注册插件对group与version的支持
  sermant-plugins/sermant-service-registry/dubbo-registry-plugin/src/main/java/com/huawei/dubbo/registry/utils/ReflectUtils.java
  sermant-plugins/sermant-service-registry/dubbo-registry-plugin/src/test/java/com/huawei/dubbo/registry/ReflectUtilsTest.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/service/RegistryServiceImpl.java
Labels: enhancement, feature

#462 【fix】降低getBytes检查（涉及非String.getBytes）、参数个数检查、捕获Exception异常的检查级别
  checkstyle.xml
Labels: bug

#465 参数问题说明和FAQ文档修改
  docs/FAQ.md
  docs/QuickStart.md
  docs/README.md
Labels: document

#464 【feature】修改checkstyle
  sermant-plugins/sermant-loadbalancer/dubbo-loadbalancer-plugin/src/test/java/com/huawei/loadbalancer/UrlInterceptorTest.java
  sermant-plugins/sermant-loadbalancer/spring-cloud-loadbalancer-plugin/src/test/java/com/huawei/loadbalancer/ClientFactoryInterceptorTest.java
  sermant-plugins/sermant-loadbalancer/spring-cloud-loadbalancer-plugin/src/test/java/com/huawei/loadbalancer/LoadBalancerInterceptorTest.java
  sermant-plugins/sermant-loadbalancer/spring-cloud-loadbalancer-plugin/src/test/java/com/huawei/loadbalancer/RibbonLoadBalancerInterceptorTest.java
  sermant-plugins/sermant-route/gray-dubbo-plugin/src/test/java/com/huawei/gray/dubbo/ReflectUtilsTest.java
  sermant-plugins/sermant-route/gray-dubbo-plugin/src/test/java/com/huawei/gray/dubbo/RegistrationInterceptorTest.java
  sermant-plugins/sermant-route/gray-dubbo-service/src/main/java/com/huawei/gray/dubbo/strategy/rule/WeightRuleStrategy.java
  sermant-plugins/sermant-route/gray-dubbo-service/src/test/java/com/huawei/gray/dubbo/service/ApplicationConfigServiceTest.java
  sermant-plugins/sermant-route/gray-dubbo-service/src/test/java/com/huawei/gray/dubbo/strategy/RuleStrategyHandlerTest.java
  sermant-plugins/sermant-route/gray-dubbo-service/src/test/java/com/huawei/gray/dubbo/strategy/TypeStrategyChooserTest.java
  sermant-plugins/sermant-route/gray-dubbo-service/src/test/java/com/huawei/gray/dubbo/strategy/type/ArrayTypeStrategyTest.java
  sermant-plugins/sermant-route/gray-dubbo-service/src/test/java/com/huawei/gray/dubbo/strategy/type/EmptyTypeStrategyTest.java
  sermant-plugins/sermant-route/gray-dubbo-service/src/test/java/com/huawei/gray/dubbo/strategy/type/Entity.java
  sermant-plugins/sermant-route/gray-dubbo-service/src/test/java/com/huawei/gray/dubbo/strategy/type/ListTypeStrategyTest.java
  sermant-plugins/sermant-route/gray-dubbo-service/src/test/java/com/huawei/gray/dubbo/strategy/type/MapTypeStrategyTest.java
  sermant-plugins/sermant-route/gray-dubbo-service/src/test/java/com/huawei/gray/dubbo/strategy/type/ObjectTypeStrategyTest.java
  sermant-plugins/sermant-route/gray-feign-http-9.x-plugin/src/main/java/com/huawei/gray/feign/definition/AbstractInstDefinition.java
  sermant-plugins/sermant-route/gray-feign-http-9.x-plugin/src/main/java/com/huawei/gray/feign/definition/HttpClientDefinition.java
  sermant-plugins/sermant-route/gray-feign-http-9.x-plugin/src/main/java/com/huawei/gray/feign/definition/LoadBalancerFeignClientDefinition.java
  sermant-plugins/sermant-route/gray-feign-http-9.x-plugin/src/main/java/com/huawei/gray/feign/definition/PathVarDefinition.java
  sermant-plugins/sermant-route/gray-feign-http-9.x-plugin/src/main/java/com/huawei/gray/feign/definition/ServiceInstanceListSupplierDefinition.java
  sermant-plugins/sermant-route/gray-feign-http-9.x-plugin/src/main/java/com/huawei/gray/feign/definition/register/EurekaClientRegisterDefinition.java
  sermant-plugins/sermant-route/gray-feign-http-9.x-plugin/src/main/java/com/huawei/gray/feign/definition/register/NacosRegisterDefinition.java
  sermant-plugins/sermant-route/gray-feign-http-9.x-plugin/src/main/java/com/huawei/gray/feign/definition/register/RegistrationDefinition.java
  sermant-plugins/sermant-route/gray-feign-http-9.x-plugin/src/main/java/com/huawei/gray/feign/definition/register/ServiceCenterRegisterDefinition.java
  sermant-plugins/sermant-route/gray-feign-http-9.x-plugin/src/main/java/com/huawei/gray/feign/definition/register/ServiceCombRegisterDefinition.java
  sermant-plugins/sermant-route/gray-feign-http-9.x-plugin/src/main/java/com/huawei/gray/feign/definition/register/ZookeeperRegisterDefinition.java
  sermant-plugins/sermant-route/gray-feign-http-9.x-plugin/src/main/java/com/huawei/gray/feign/interceptor/RegisterInterceptor.java
  sermant-plugins/sermant-route/gray-feign-http-9.x-plugin/src/main/java/com/huawei/gray/feign/service/DefaultHttpClientService.java
  sermant-plugins/sermant-route/gray-feign-http-9.x-plugin/src/main/java/com/huawei/gray/feign/service/LoadBalancerClientService.java
  sermant-plugins/sermant-route/gray-feign-http-9.x-plugin/src/main/java/com/huawei/gray/feign/service/PathVarService.java
  sermant-plugins/sermant-route/gray-feign-http-9.x-plugin/src/main/java/com/huawei/gray/feign/service/RegisterService.java
  sermant-plugins/sermant-route/gray-feign-http-9.x-service/pom.xml
  sermant-plugins/sermant-route/gray-feign-http-9.x-service/src/main/java/com/huawei/gray/feign/context/CurrentInstance.java
  sermant-plugins/sermant-route/gray-feign-http-9.x-service/src/main/java/com/huawei/gray/feign/context/FeignResolvedUrl.java
  sermant-plugins/sermant-route/gray-feign-http-9.x-service/src/main/java/com/huawei/gray/feign/rule/RuleStrategy.java
  sermant-plugins/sermant-route/gray-feign-http-9.x-service/src/main/java/com/huawei/gray/feign/rule/RuleType.java
  sermant-plugins/sermant-route/gray-feign-http-9.x-service/src/main/java/com/huawei/gray/feign/rule/UpstreamRuleStrategy.java
  sermant-plugins/sermant-route/gray-feign-http-9.x-service/src/main/java/com/huawei/gray/feign/rule/WeightRuleStrategy.java
  sermant-plugins/sermant-route/gray-feign-http-9.x-service/src/main/java/com/huawei/gray/feign/service/ConfigServiceImpl.java
  sermant-plugins/sermant-route/gray-feign-http-9.x-service/src/main/java/com/huawei/gray/feign/service/DefaultHttpClientServiceImpl.java
  sermant-plugins/sermant-route/gray-feign-http-9.x-service/src/main/java/com/huawei/gray/feign/service/LoadBalancerClientServiceImpl.java
  sermant-plugins/sermant-route/gray-feign-http-9.x-service/src/main/java/com/huawei/gray/feign/service/PathVarServiceImpl.java
  sermant-plugins/sermant-route/gray-feign-http-9.x-service/src/main/java/com/huawei/gray/feign/service/RegisterServiceImpl.java
  sermant-plugins/sermant-route/gray-feign-http-9.x-service/src/main/java/com/huawei/gray/feign/util/RouterUtil.java
  sermant-plugins/sermant-route/route-common/src/main/java/com/huawei/route/common/gray/addr/entity/Instances.java
  sermant-plugins/sermant-route/route-common/src/main/java/com/huawei/route/common/gray/label/entity/GrayConfiguration.java
  sermant-plugins/sermant-route/route-common/src/main/java/com/huawei/route/common/gray/label/entity/Match.java
  sermant-plugins/sermant-route/route-common/src/main/java/com/huawei/route/common/gray/label/entity/MatchRule.java
  sermant-plugins/sermant-route/route-common/src/main/java/com/huawei/route/common/gray/label/entity/Route.java
  sermant-plugins/sermant-route/route-common/src/test/java/com/huawei/route/common/gray/strategy/match/MatchStrategyTest.java
  sermant-plugins/sermant-service-registry/dubbo-registry-plugin/src/main/java/com/huawei/dubbo/registry/utils/ReflectUtils.java
  sermant-plugins/sermant-service-registry/dubbo-registry-plugin/src/test/java/com/huawei/dubbo/registry/ExtensionLoaderInterceptorTest.java
  sermant-plugins/sermant-service-registry/dubbo-registry-plugin/src/test/java/com/huawei/dubbo/registry/MigrationRuleInterceptorTest.java
  sermant-plugins/sermant-service-registry/dubbo-registry-plugin/src/test/java/com/huawei/dubbo/registry/ReflectUtilsTest.java
  sermant-plugins/sermant-service-registry/dubbo-registry-plugin/src/test/java/com/huawei/dubbo/registry/RegistryFactoryTest.java
  sermant-plugins/sermant-service-registry/dubbo-registry-plugin/src/test/java/com/huawei/dubbo/registry/RegistryProtocolInterceptorTest.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/service/RegistryConfigServiceImpl.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/test/java/com/huawei/dubbo/registry/RegistryConfigServiceTest.java
  sermant-plugins/sermant-service-registry/registry-common/src/main/java/com/huawei/registry/config/RegisterConfig.java
Labels: document
