Repository sermant-io/Sermant, pull requests merged in 2022-01, with the labels that each got.

#313 【BUG】修复zk动态配置实现中遍历子节点时带有'/'的问题
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/dynamicconfig/zookeeper/ZooKeeperDynamicConfigService.java
Labels: bug

#319 【BUG】更新netty、protobuf和logback的版本，避免低版本依赖的bug
  pom.xml
  sermant-agentcore/sermant-agentcore-core/pom.xml
  sermant-plugins/sermant-flowrecord/flowrecord-replay/pom.xml
Labels: bug

#321 【DOC】更新插件功能列表文档
  docs/README.md
  docs/user-guide/feature-list.md
Labels: documentation

#309 门禁增加代码规范检查
  .github/workflows/maven.yml
  checkstyle.xml
Labels: enhancement
