Repository sermant-io/Sermant, pull requests merged in 2022-12, with the labels that each got.

#1006 【feature】重构优化插件类隔离机制
  pom.xml
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/classloader/ClassLoaderManager.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/classloader/CommonClassLoader.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/classloader/FrameworkClassLoader.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/common/CommonConstant.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/plugin/PluginManager.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/plugin/classloader/PluginClassLoader.java
  sermant-agentcore/sermant-agentcore-implement/src/main/java/com/huaweicloud/sermant/implement/operation/adaptor/AdaptorManagerImpl.java
  sermant-agentcore/sermant-agentcore-premain/src/main/java/com/huawei/sermant/premain/common/BootArgsBuilder.java
  sermant-agentcore/sermant-agentcore-premain/src/main/java/com/huawei/sermant/premain/common/PathDeclarer.java
  sermant-common-dependency/pom.xml
Labels: kind/enhancement, lgtm

#1012 【fix】fix the bug that springboot registry plugin can not process the url query params
  sermant-plugins/sermant-springboot-registry/springboot-registry-plugin/src/main/java/com/huawei/discovery/utils/RequestInterceptorUtils.java
Labels: kind/bug, area/plugin

#1013 【fix】fix the bug that springboot registry plugin can not process the url query params
  sermant-plugins/sermant-loadbalancer/dubbo-loadbalancer-plugin/src/main/java/com/huaweicloud/loadbalancer/declarer/UrlDeclarer.java
  sermant-plugins/sermant-loadbalancer/dubbo-loadbalancer-plugin/src/main/java/com/huaweicloud/loadbalancer/interceptor/UrlInterceptor.java
  sermant-plugins/sermant-springboot-registry/springboot-registry-plugin/src/main/java/com/huawei/discovery/utils/RequestInterceptorUtils.java
Labels: kind/bug, area/plugin

#1011 【doc】sermant-common重命名以及文档更新
  docs/dev-guide/dev_plugin_introduce-zh.md
  docs/dev-guide/dev_plugin_introduce.md
  docs/dev-guide/dev_plugin_module-zh.md
  docs/dev-guide/dev_plugin_module.md
  pom.xml
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/classloader/CommonClassLoader.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/common/CommonConstant.java
  sermant-agentcore/sermant-agentcore-premain/src/main/java/com/huawei/sermant/premain/common/PathDeclarer.java
  sermant-common-dependency/pom.xml
  sermant-common/pom.xml
Labels: kind/enhancement, docs, lgtm

#1009 【refactor】清理lubanadaptor及框架中的适配器逻辑
  sermant-agentcore/sermant-agentcore-config/config/plugins.yaml
  sermant-agentcore/sermant-agentcore-config/config/test/plugins.yaml
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/operation/adaptor/api/AdaptorManager.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/operation/adaptor/common/AdaptorConstants.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/operation/adaptor/config/AdaptorConfig.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/operation/adaptor/config/AdaptorSetting.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/plugin/PluginSystemEntrance.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/plugin/agent/collector/AdaptorCollector.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/plugin/agent/collector/AdaptorCollectorManager.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/plugin/service/AdaptorService.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/plugin/service/AdaptorServiceManager.java
  sermant-agentcore/sermant-agentcore-core/src/main/resources/META-INF/services/com.huaweicloud.sermant.core.config.common.BaseConfig
  sermant-agentcore/sermant-agentcore-core/src/main/resources/META-INF/services/com.huaweicloud.sermant.core.plugin.agent.collector.PluginCollector
  sermant-agentcore/sermant-agentcore-implement/src/main/java/com/huaweicloud/sermant/implement/operation/adaptor/AdaptorManagerImpl.java
  sermant-agentcore/sermant-agentcore-implement/src/main/java/com/huaweicloud/sermant/implement/operation/adaptor/remapper/AdaptorRemapper.java
  sermant-agentcore/sermant-agentcore-implement/src/main/java/com/huaweicloud/sermant/implement/operation/adaptor/remapper/AdaptorShader.java
  sermant-agentcore/sermant-agentcore-implement/src/main/resources/META-INF/services/com.huaweicloud.sermant.core.operation.BaseOperation
  sermant-plugins/pom.xml
  sermant-plugins/sermant-luban-adaptor/config/config.yaml
  sermant-plugins/sermant-luban-adaptor/lib/apm-javaagent.jar
  sermant-plugins/sermant-luban-adaptor/lib/boot/lubanops-apm-javaagent-bootstrap-2.0.5.jar
  sermant-plugins/sermant-luban-adaptor/lib/core/lubanops-apm-javaagent-core-2.0.5.jar
  sermant-plugins/sermant-luban-adaptor/pom.xml
  sermant-plugins/sermant-luban-adaptor/src/main/java/com/huawei/sermant/plugins/luban/adaptor/collector/AttributeAccessImplTemplate.java
  sermant-plugins/sermant-luban-adaptor/src/main/java/com/huawei/sermant/plugins/luban/adaptor/collector/BufferedTransformAccess.java
  sermant-plugins/sermant-luban-adaptor/src/main/java/com/huawei/sermant/plugins/luban/adaptor/collector/LubanListenerCollector.java
  sermant-plugins/sermant-luban-adaptor/src/main/java/com/huawei/sermant/plugins/luban/adaptor/declarer/InterceptorTransformer.java
  sermant-plugins/sermant-luban-adaptor/src/main/java/com/huawei/sermant/plugins/luban/adaptor/declarer/LubanPluginDeclarer.java
  sermant-plugins/sermant-luban-adaptor/src/main/java/com/huawei/sermant/plugins/luban/adaptor/declarer/LubanPluginDescription.java
  sermant-plugins/sermant-luban-adaptor/src/main/java/com/huawei/sermant/plugins/luban/adaptor/matcher/GetterSetterMatcher.java
  sermant-plugins/sermant-luban-adaptor/src/main/java/com/huawei/sermant/plugins/luban/adaptor/service/LubanAdaptorService.java
  sermant-plugins/sermant-luban-adaptor/src/main/java/com/huawei/sermant/plugins/luban/adaptor/service/LubanTransformerAdviser.java
  sermant-plugins/sermant-luban-adaptor/src/main/resources/META-INF/services/com.huaweicloud.sermant.core.plugin.agent.collector.AdaptorCollector
  sermant-plugins/sermant-luban-adaptor/src/main/resources/META-INF/services/com.huaweicloud.sermant.core.plugin.service.AdaptorService
Labels: kind/refactor

#1015 【fix】修复sermant-common中心仓出包问题
  sermant-common/pom.xml
Labels: release

#1018 【fix】修改流控测试用例，修复测试失败问题
  sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/test/java/com/huawei/fowcontrol/res4j/chain/handler/CircuitRequestHandlerTest.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/test/java/com/huawei/fowcontrol/res4j/chain/handler/RequestHandlerTest.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/test/java/com/huawei/fowcontrol/res4j/handler/HandlerTest.java
Labels: kind/bug, area/plugin

#1008 【feature】增加dubbo注册Nacos能力的服务实现
  LICENSE
  sermant-plugins/sermant-service-registry/dubbo-registry-plugin/src/main/java/com/huawei/dubbo/registry/utils/ReflectUtils.java
  sermant-plugins/sermant-service-registry/dubbo-registry-plugin/src/test/java/com/huawei/dubbo/registry/ReflectUtilsTest.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/pom.xml
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/entity/NacosServiceName.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/factory/RegistryNotifyThreadFactory.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/listener/NacosAggregateListener.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/service/NacosRegistryServiceImpl.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/service/NacosServiceNotify.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/service/RegistryNotifier.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/utils/NacosInstanceManageUtil.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/utils/NamingServiceUtils.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/resources/META-INF/services/com.huaweicloud.sermant.core.plugin.service.PluginService
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/test/java/com/huawei/dubbo/registry/NacosAggregateListenerTest.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/test/java/com/huawei/dubbo/registry/NacosInstanceManageUtilTest.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/test/java/com/huawei/dubbo/registry/NacosRegistryServiceImplTest.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/test/java/com/huawei/dubbo/registry/NacosServiceNameTest.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/test/java/com/huawei/dubbo/registry/NamingServiceUtilsTest.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/test/java/com/huawei/dubbo/registry/RegistryNotifierTest.java
Labels: kind/enhancement, lgtm

#1036 【fix】修改流控测试用例，修复测试失败问题
  sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/test/java/com/huawei/fowcontrol/res4j/chain/handler/CircuitRequestHandlerTest.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/test/java/com/huawei/fowcontrol/res4j/chain/handler/RequestHandlerTest.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/test/java/com/huawei/fowcontrol/res4j/handler/HandlerTest.java
Labels: kind/bug, kind/enhancement

#1033 【bug】修复jul日志级别与logback不一致的问题
  sermant-agentcore/sermant-agentcore-implement/src/main/java/com/huaweicloud/sermant/implement/LoggerFactoryImpl.java
Labels: kind/bug, area/core, lgtm

#1034 【bug】修复jul日志级别与logback不一致的问题
  sermant-agentcore/sermant-agentcore-implement/src/main/java/com/huaweicloud/sermant/implement/LoggerFactoryImpl.java
Labels: kind/bug, area/core

#1030 【enhance】支持injector以maven依赖包的形式引入
  pom.xml
  sermant-injector/pom.xml
  sermant-injector/src/main/java/com/huaweicloud/sermant/injection/annotation/EnableSermantInjector.java
  sermant-injector/src/main/java/com/huaweicloud/sermant/injection/controller/SermantInjectorController.java
  sermant-injector/src/test/java/com/huaweicloud/sermant/injection/controller/SermantInjectorControllerTest.java
Labels: kind/feature, lgtm, area/injector

#1028 【fix】修改有安全漏洞的依赖版本
  sermant-backend-lite/pom.xml
  sermant-backend/pom.xml
  sermant-plugins/sermant-service-registry/dubbo-registry-service/pom.xml
  sermant-plugins/sermant-service-registry/spring-cloud-registry-service/pom.xml
Labels: kind/enhancement, lgtm

#1038 【fix】插件服务第三方依赖的logback日志配置优先使用sermant配置
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/plugin/classloader/PluginClassLoader.java
Labels: kind/enhancement

#1040 【fix】修改 javadoc执行失败
  sermant-common/src/main/java/com/huawei/common/Application.java
Labels: kind/enhancement

#1042 【question】支持环境变量设置注册中心类型
  sermant-injector/src/main/java/com/huaweicloud/sermant/injection/controller/SermantInjectorController.java
  sermant-injector/src/main/resources/application.yml
Labels: kind/enhancement

#1046 【question】调整注册中心地址为公共参数
  docs/user-guide/registry/document-zh.md
  docs/user-guide/registry/document.md
  sermant-plugins/sermant-service-registry/config/config.yaml
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/service/NacosRegistryServiceImpl.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/service/RegistryServiceImpl.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/utils/NamingServiceUtils.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/test/java/com/huawei/dubbo/registry/NacosRegistryServiceImplTest.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/test/java/com/huawei/dubbo/registry/NacosServiceNameTest.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/test/java/com/huawei/dubbo/registry/NamingServiceUtilsTest.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/test/java/com/huawei/dubbo/registry/RegistryServiceTest.java
  sermant-plugins/sermant-service-registry/registry-common/src/main/java/com/huawei/registry/config/NacosRegisterConfig.java
  sermant-plugins/sermant-service-registry/registry-common/src/main/java/com/huawei/registry/config/RegisterConfig.java
  sermant-plugins/sermant-service-registry/registry-common/src/main/java/com/huawei/registry/config/RegisterServiceCommonConfig.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-service/src/main/java/com/huawei/registry/service/client/ScClient.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-service/src/test/java/com/huawei/registry/service/register/NacosServiceManagerTest.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-service/src/test/java/com/huawei/registry/service/register/ScRegisterTest.java
Labels: kind/enhancement, lgtm

#1048 【test】add config match strategy test for router plugin
  sermant-integration-tests/spring-test/spring-intergration-test/src/test/java/com/huaweicloud/intergration/router/TagRouterTest.java
Labels: kind/enhancement, area/test

#1056 【feature】支持injector通过helm模版配置环境变量
  sermant-injector/deployment/release/injector/templates/sermant-agent-env-configmap.yaml
  sermant-injector/deployment/release/injector/values.yaml
  sermant-injector/src/main/java/com/huaweicloud/sermant/injection/controller/SermantInjectorController.java
  sermant-injector/src/main/resources/application.yml
Labels: kind/enhancement, lgtm, area/injector

#1058 修改版本漏洞
  pom.xml
  sermant-backend-lite/pom.xml
  sermant-plugins/sermant-service-registry/dubbo-registry-service/pom.xml
  sermant-plugins/sermant-service-registry/spring-cloud-registry-service/pom.xml
Labels: kind/bug, lgtm

#1050 【test】add auto test for springcloud registry plugin and flowcontrol plugin
  .github/actions/scenarios/spring/spring-common/action.yml
  sermant-integration-tests/dubbo-test/dubbo-2-6-integration-consumer/src/main/resources/rule.yaml
  sermant-integration-tests/dubbo-test/dubbo-2-7-integration-consumer/src/main/resources/rule.yaml
  sermant-integration-tests/dubbo-test/dubbo-integration-api/src/main/java/com/huaweicloud/integration/controller/FlowController.java
  sermant-integration-tests/dubbo-test/dubbo-integration-api/src/main/java/com/huaweicloud/integration/service/FlowControlService.java
  sermant-integration-tests/dubbo-test/dubbo-integration-api/src/main/java/com/huaweicloud/integration/service/impl/FlowControlServiceImpl.java
  sermant-integration-tests/dubbo-test/dubbo-integration-test/src/test/java/com/huaweicloud/integration/flow/FlowControlTest.java
  sermant-integration-tests/spring-test/spring-common-demos/spring-common-feign-1.5.x/feign-api-1.5.x/src/main/java/com/huaweicloud/spring/feign/api/Feign15xService.java
  sermant-integration-tests/spring-test/spring-common-demos/spring-common-feign-1.5.x/feign-api-1.5.x/src/main/java/com/huaweicloud/spring/feign/api/HeaderMatchConfiguration.java
  sermant-integration-tests/spring-test/spring-common-demos/spring-common-feign-1.5.x/feign-consumer-1.5.x/src/main/java/com/huaweicloud/spring/feign/consumer/controller/FlowController.java
  sermant-integration-tests/spring-test/spring-common-demos/spring-common-feign-1.5.x/feign-consumer-1.5.x/src/main/resources/rule.yaml
  sermant-integration-tests/spring-test/spring-common-demos/spring-common-feign/feign-api/src/main/java/com/huaweicloud/spring/feign/api/FeignService.java
  sermant-integration-tests/spring-test/spring-common-demos/spring-common-feign/feign-api/src/main/java/com/huaweicloud/spring/feign/api/configuration/HeaderMatchConfiguration.java
  sermant-integration-tests/spring-test/spring-common-demos/spring-common-feign/feign-consumer/src/main/java/com/huaweicloud/spring/feign/consumer/controller/FlowController.java
  sermant-integration-tests/spring-test/spring-common-demos/spring-common-feign/feign-consumer/src/main/resources/rule.yaml
  sermant-integration-tests/spring-test/spring-common-demos/spring-common-resttemplate/rest-consumer/src/main/resources/rule.yaml
  sermant-integration-tests/spring-test/spring-common/src/main/java/com/huaweicloud/spring/common/flowcontrol/consumer/ServerController.java
  sermant-integration-tests/spring-test/spring-common/src/main/java/com/huaweicloud/spring/common/flowcontrol/provider/ProviderController.java
  sermant-integration-tests/spring-test/spring-intergration-test/src/test/java/com/huaweicloud/intergration/flowcontrol/FlowControlTest.java
  sermant-integration-tests/spring-test/spring-intergration-test/src/test/java/com/huaweicloud/intergration/registry/cloud/CloudRegistryTest.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/interceptors/DynamicServerListInterceptor.java
Labels: kind/bug, area/plugin, area/test

#1054 【enhance】Optimize plugins
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/utils/ReflectUtils.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/java/com/huawei/flowcontrol/res4j/chain/AbstractChainHandler.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/java/com/huawei/flowcontrol/res4j/chain/HandlerChainEntry.java
  sermant-plugins/sermant-router/dubbo-router-plugin/src/main/java/com/huaweicloud/sermant/router/dubbo/interceptor/ContextFilterInterceptor.java
  sermant-plugins/sermant-router/dubbo-router-plugin/src/main/java/com/huaweicloud/sermant/router/dubbo/utils/DubboReflectUtils.java
  sermant-plugins/sermant-router/dubbo-router-service/src/main/java/com/huaweicloud/sermant/router/dubbo/service/AbstractDirectoryServiceImpl.java
  sermant-plugins/sermant-router/dubbo-router-service/src/main/java/com/huaweicloud/sermant/router/dubbo/strategy/RuleStrategyHandler.java
  sermant-plugins/sermant-router/dubbo-router-service/src/main/java/com/huaweicloud/sermant/router/dubbo/strategy/instance/MatchInstanceStrategy.java
  sermant-plugins/sermant-router/dubbo-router-service/src/main/java/com/huaweicloud/sermant/router/dubbo/strategy/instance/MismatchInstanceStrategy.java
  sermant-plugins/sermant-router/router-common/src/main/java/com/huaweicloud/sermant/router/common/utils/ReflectUtils.java
  sermant-plugins/sermant-router/router-config-common/src/main/java/com/huaweicloud/sermant/router/config/strategy/AbstractRuleStrategy.java
  sermant-plugins/sermant-router/router-config-common/src/main/java/com/huaweicloud/sermant/router/config/strategy/RuleStrategy.java
  sermant-plugins/sermant-router/router-config-common/src/main/java/com/huaweicloud/sermant/router/config/utils/RuleUtils.java
  sermant-plugins/sermant-router/router-config-common/src/test/java/com/huaweicloud/sermant/router/config/utils/RuleUtilsTest.java
  sermant-plugins/sermant-router/spring-router-plugin/src/main/java/com/huaweicloud/sermant/router/spring/interceptor/BaseLoadBalancerInterceptor.java
  sermant-plugins/sermant-router/spring-router-plugin/src/main/java/com/huaweicloud/sermant/router/spring/interceptor/FeignClientInterceptor.java
  sermant-plugins/sermant-router/spring-router-plugin/src/main/java/com/huaweicloud/sermant/router/spring/interceptor/HystrixActionInterceptor.java
  sermant-plugins/sermant-router/spring-router-plugin/src/main/java/com/huaweicloud/sermant/router/spring/interceptor/RouteHandlerInterceptor.java
  sermant-plugins/sermant-router/spring-router-service/src/main/java/com/huaweicloud/sermant/router/spring/service/LoadBalancerServiceImpl.java
  sermant-plugins/sermant-router/spring-router-service/src/main/java/com/huaweicloud/sermant/router/spring/strategy/RuleStrategyHandler.java
Labels: kind/enhancement, area/plugin

#1063 【question】Nacos注册实例增加parameters作为标签路由内容
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/service/NacosRegistryServiceImpl.java
Labels: kind/enhancement, lgtm

#1060 【fix】修复某些服务加载失败问题导致宿主应用无法正常提供服务
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/plugin/subscribe/AbstractGroupConfigSubscriber.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/init/FlowControlInitServiceImpl.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/auto/sc/ServiceCombRegistry.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/inject/grace/ContextClosedEventListener.java
Labels: kind/bug, area/core, lgtm, area/plugin

#1065 优化标签路由全集配置解析
  sermant-plugins/sermant-router/router-config-service/src/main/java/com/huaweicloud/sermant/router/config/handler/RouterConfigHandler.java
Labels: kind/enhancement, lgtm

#1061 PR for #1037, 容器部署场景下，希望能通过annotation的方式配置治理所需的kv属性或者标签
  sermant-injector/src/main/java/com/huaweicloud/sermant/injection/controller/SermantInjectorController.java
  sermant-injector/src/test/java/com/huaweicloud/sermant/injection/controller/SermantInjectorControllerTest.java
  sermant-injector/src/test/resources/test.json
Labels: kind/enhancement

#1067 【enhance】简化injector部署流程，使用helm获取证书与caBundle值
  sermant-injector/deployment/release/injector/templates/sermant-injector-ns.yaml
  sermant-injector/deployment/release/injector/templates/sermant-injector-webhook.yaml
  sermant-injector/deployment/release/injector/values.yaml
  sermant-injector/scripts/certificate.sh
Labels: kind/enhancement, area/injector
