Repository sermant-io/Sermant, pull requests merged in 2022-04, with the labels that each got.

#473 【fix】恢复ParameterNumber、IllegalThrows、ParameterAssignment、IllegalCatch的提示级别
  checkstyle.xml
Labels: enhancement

#469 【fix】修复流控dubbo2.7.3-2.7.4出现的空指针问题
  docs/user-guide/flowcontrol/flowcontrol.md
  sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/config/CommonConst.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/AlibabaDubboInterceptor.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/ApacheDubboInterceptor.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/AlibabaDubboInvokerInterceptor.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/HttpRequestDeclarer.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/HttpRequestInterceptor.java
Labels: bug

#468 【fix】清理agentcore、lubanadaptor、servermonitor的@Supresswarning注解
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/agent/matcher/ClassMatchers.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/plugin/adaptor/config/AdaptorConfig.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/plugin/adaptor/remapper/AdaptorShader.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/plugin/agent/BufferedAgentBuilder.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/plugin/agent/config/AgentConfig.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/plugin/agent/declarer/InterceptDeclarer.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/plugin/agent/entity/ExecuteContext.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/plugin/agent/matcher/ClassMatcher.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/plugin/agent/matcher/MethodMatcher.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/plugin/agent/template/AdviceConstTemplate.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/plugin/agent/template/AdviceMemberTemplate.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/plugin/agent/template/AdviceStaticTemplate.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/plugin/agent/template/BootstrapConstTemplate.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/plugin/agent/template/BootstrapMemberTemplate.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/plugin/agent/template/BootstrapStaticTemplate.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/plugin/agent/template/CommonBaseAdviser.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/plugin/agent/transformer/BootstrapTransformer.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/dynamicconfig/BufferedDynamicConfigService.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/dynamicconfig/DynamicConfigService.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/dynamicconfig/kie/KieDynamicConfigService.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/dynamicconfig/kie/listener/SubscriberManager.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/dynamicconfig/nop/NopDynamicConfigService.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/dynamicconfig/zookeeper/ZooKeeperDynamicConfigService.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/heartbeat/HeartbeatServiceImpl.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/utils/NetworkUtils.java
  sermant-agentcore/sermant-agentcore-premain/src/main/java/com/huawei/sermant/premain/AgentPremain.java
  sermant-plugins/sermant-luban-adaptor/src/main/java/com/huawei/sermant/plugins/luban/adaptor/service/LubanTransformerAdviser.java
  sermant-plugins/sermant-server-monitor/connection-pool-collect-plugin/pom.xml
  sermant-plugins/sermant-server-monitor/connection-pool-collect-plugin/src/main/java/com/huawei/sermant/plugin/connection/pool/collect/collector/DruidMetricCollector.java
  sermant-plugins/sermant-server-monitor/connection-pool-collect-plugin/src/main/java/com/huawei/sermant/plugin/connection/pool/collect/collector/DruidMetricProvider.java
  sermant-plugins/sermant-server-monitor/databasepeer-parse-service/pom.xml
  sermant-plugins/sermant-server-monitor/databasepeer-parse-service/src/main/java/com/huawei/sermant/plugin/databasepeerparse/service/DatabasePeerParseServiceImpl.java
  sermant-plugins/sermant-server-monitor/monitor-common/pom.xml
  sermant-plugins/sermant-server-monitor/monitor-common/src/main/java/com/huawei/sermant/plugin/monitor/common/service/DatabasePeerParseService.java
Labels: enhancement

#475 默认编译选项添加backend模块
  pom.xml
Labels: bug

#467 【fix】suppress-checkstyle去除
  sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/adapte/cse/converter/YamlConverter.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/adapte/cse/entity/CseServiceMeta.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/adapte/cse/match/MatchGroupResolver.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/adapte/cse/resolver/AbstractResolver.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/config/FlowControlConfig.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/AlibabaDubboInvokerInterceptor.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/ApacheDubboInvokerInterceptor.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/FeignRequestInterceptor.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/HttpRequestInterceptor.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/cluster/AlibabaDubboClusterInvoker.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/cluster/ApacheDubboClusterInvoker.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/service/DubboService.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/java/com/huawei/fowcontrol/res4j/service/DubboRest4jServiceImpl.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/java/com/huawei/fowcontrol/res4j/service/HttpRest4jServiceImpl.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/test/java/com/huawei/fowcontrol/res4j/handler/HandlerFacadeTest.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/config/RegisterDynamicConfig.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/config/RegisterDynamicConfigSyncer.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/context/RegisterContext.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/handler/SingleStateCloseHandler.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/interceptors/DiscoveryClientInterceptor.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/interceptors/ServerListInterceptor.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/interceptors/health/NacosHealthInterceptor.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/support/FieldAccessAction.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/utils/CommonUtils.java
Labels: enhancement

#478 【fix】修改codecheck问题
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/exception/DupConfIndexException.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/exception/DupServiceException.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/exception/SchemaException.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/dynamicconfig/common/DynamicConfigEvent.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/dynamicconfig/kie/client/http/HttpResult.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/dynamicconfig/kie/client/kie/KieClient.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/dynamicconfig/zookeeper/ZooKeeperInitException.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/heartbeat/HeartbeatServiceImpl.java
  sermant-agentcore/sermant-agentcore-core/src/test/java/com/huawei/sermant/core/service/dynamicconfig/KieDynamicConfigServiceTest.java
  sermant-agentcore/sermant-agentcore-core/src/test/java/com/huawei/sermant/core/service/dynamicconfig/kie/PublishTest.java
  sermant-agentcore/sermant-agentcore-premain/pom.xml
  sermant-agentcore/sermant-agentcore-premain/src/main/java/com/huawei/sermant/premain/common/BootArgsBuilder.java
  sermant-agentcore/sermant-agentcore-premain/src/main/java/com/huawei/sermant/premain/exception/DupPremainException.java
  sermant-agentcore/sermant-agentcore-premain/src/main/java/com/huawei/sermant/premain/exception/InitPremainException.java
Labels: enhancement

#476 默认编译选项添加package模块
  pom.xml
Labels: enhancement

#482 backend删除前端编译结果，前端编译部分加入backend打包阶段
  sermant-backend/pom.xml
  sermant-backend/src/main/webapp/frontend/dist/index.html
  sermant-backend/src/main/webapp/frontend/dist/static/css/app.css
  sermant-backend/src/main/webapp/frontend/dist/static/css/app.css.map
  sermant-backend/src/main/webapp/frontend/dist/static/js/app.js
  sermant-backend/src/main/webapp/frontend/dist/static/js/app.js.map
  sermant-backend/src/main/webapp/frontend/dist/static/js/manifest.js
  sermant-backend/src/main/webapp/frontend/dist/static/js/manifest.js.map
  sermant-backend/src/main/webapp/frontend/dist/static/js/vendor.js
  sermant-backend/src/main/webapp/frontend/dist/static/js/vendor.js.map
  sermant-backend/src/main/webapp/frontend/package-lock.json
Labels: enhancement

#479 【feature】流控支持批量配置模式并支持dubbo泛化接口调用
  sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/adapte/cse/ResolverManager.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/adapte/cse/match/MatchGroupResolver.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/adapte/cse/rule/syncer/RuleDynamicConfigListener.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/config/CommonConst.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/util/ConvertUtils.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/util/StringUtils.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/AlibabaDubboInterceptor.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/ApacheDubboInterceptor.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/AlibabaDubboInvokerInterceptor.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/ApacheDubboInvokerInterceptor.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/cluster/AlibabaDubboClusterInvoker.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/cluster/ApacheDubboClusterInvoker.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/service/InterceptorSupporter.java
Labels: bug

#486 【fix】流控插件熔断配置恢复时间与时间窗口解析优化
  docs/user-guide/flowcontrol/FAQ.md
  docs/user-guide/flowcontrol/flowcontrol.md
  sermant-plugins/sermant-flowcontrol/config/config.yaml
  sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/adapte/cse/ResolverManager.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/adapte/cse/resolver/AbstractResolver.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/adapte/cse/rule/AbstractRule.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/adapte/cse/rule/CircuitBreakerRule.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/adapte/cse/rule/syncer/RuleDynamicConfigListener.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/java/com/huawei/fowcontrol/res4j/handler/CircuitBreakerHandler.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/java/com/huawei/fowcontrol/res4j/handler/HandlerFacade.java
Labels: bug

#489 【feature】整理example，用于对agentcore进行基线测试
  sermant-example/demo-application/src/main/java/com/huawei/example/demo/DemoApplication.java
  sermant-example/demo-application/src/main/java/com/huawei/example/demo/service/DemoAnnotation.java
  sermant-example/demo-application/src/main/java/com/huawei/example/demo/service/DemoNameService.java
  sermant-example/demo-application/src/main/java/com/huawei/example/demo/service/DemoSuperTypeService.java
  sermant-example/demo-application/src/main/java/com/huawei/example/demo/service/DemoTraceService.java
  sermant-example/demo-plugin/src/main/java/com/huawei/example/demo/declarer/DemoAnnotationDeclarer.java
  sermant-example/demo-plugin/src/main/java/com/huawei/example/demo/declarer/DemoNameDeclarer.java
  sermant-example/demo-plugin/src/main/java/com/huawei/example/demo/declarer/DemoNameInfixDeclarer.java
  sermant-example/demo-plugin/src/main/java/com/huawei/example/demo/declarer/DemoNamePrefixDeclarer.java
  sermant-example/demo-plugin/src/main/java/com/huawei/example/demo/declarer/DemoNameSuffixDeclarer.java
  sermant-example/demo-plugin/src/main/java/com/huawei/example/demo/declarer/DemoSuperTypeDeclarer.java
  sermant-example/demo-plugin/src/main/java/com/huawei/example/demo/declarer/DemoTraceDeclarer.java
  sermant-example/demo-plugin/src/main/java/com/huawei/example/demo/interceptor/DemoConstInterceptor.java
  sermant-example/demo-plugin/src/main/java/com/huawei/example/demo/interceptor/DemoFieldCheckInterceptor.java
  sermant-example/demo-plugin/src/main/java/com/huawei/example/demo/interceptor/DemoMemberInterceptor.java
  sermant-example/demo-plugin/src/main/java/com/huawei/example/demo/interceptor/DemoStaticInterceptor.java
  sermant-example/demo-plugin/src/main/java/com/huawei/example/demo/interceptor/DemoTraceConsumerInterceptor.java
  sermant-example/demo-plugin/src/main/java/com/huawei/example/demo/interceptor/DemoTraceNormalInterceptor.java
  sermant-example/demo-plugin/src/main/java/com/huawei/example/demo/interceptor/DemoTraceProviderInterceptor.java
  sermant-example/demo-plugin/src/main/resources/META-INF/services/com.huawei.sermant.core.plugin.agent.declarer.PluginDeclarer
Labels: enhancement

#491 心跳写入kafka格式修改
  sermant-backend/src/main/java/com/huawei/sermant/backend/server/ServerHandler.java
Labels: bug

#495 【fix】修复增强启动类加载器加载类会被添加static块导致redefine抛出异常的问题
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/plugin/agent/BufferedAgentBuilder.java
Labels: bug

#497 【feature】优化dubbo注册插件
  checkstyle.xml
  sermant-plugins/sermant-service-registry/dubbo-registry-plugin/src/main/java/com/huawei/dubbo/registry/constants/Constant.java
  sermant-plugins/sermant-service-registry/dubbo-registry-plugin/src/main/java/com/huawei/dubbo/registry/utils/ReflectUtils.java
  sermant-plugins/sermant-service-registry/dubbo-registry-plugin/src/test/java/com/huawei/dubbo/registry/ReflectUtilsTest.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/pom.xml
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/InterfaceData.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/InterfaceKey.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/Subscription.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/SubscriptionKey.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/service/RegistryServiceImpl.java
Labels: enhancement, feature

#509 【fix】Field设置成员变量的值时指定被拦截类的对象
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/plugin/agent/entity/ExecuteContext.java
Labels: bug

#507 【BUG】修复没有kafka服务时，backend数据处理阻塞问题
  sermant-backend/src/main/java/com/huawei/sermant/backend/server/NettyServer.java
  sermant-backend/src/main/java/com/huawei/sermant/backend/server/ServerHandler.java
  sermant-backend/src/test/java/com/huawei/sermant/backend/NettyServerTest.java
Labels: bug

#511 添加backend缓存开关说明
  docs/user-guide/backend.md
Labels: document

#513 【feature】新增dubbo注册插件开关，并修改相关文档与demo应用
  checkstyle.xml
  docs/FAQ.md
  docs/binary-docs/registry-faq-7.png
  docs/binary-docs/registry-faq-8.png
  docs/user-guide/registry/FAQ.md
  docs/user-guide/registry/document.md
  docs/user-guide/registry/dubbo-registry-migiration.md
  docs/user-guide/registry/spring-cloud-registry-migiration.md
  sermant-plugins/sermant-service-registry/config/config.yaml
  sermant-plugins/sermant-service-registry/demo-registry/demo-registry-dubbo/dubbo-consumer/src/main/resources/application.yaml
  sermant-plugins/sermant-service-registry/demo-registry/demo-registry-dubbo/dubbo-provider/src/main/java/com/huawei/dubbotest/impl/TestInterfaceImpl.java
  sermant-plugins/sermant-service-registry/demo-registry/demo-registry-dubbo/dubbo-provider/src/main/resources/application.yaml
  sermant-plugins/sermant-service-registry/dubbo-registry-plugin/src/main/java/com/huawei/dubbo/registry/constants/Constant.java
  sermant-plugins/sermant-service-registry/dubbo-registry-plugin/src/main/java/com/huawei/dubbo/registry/declarer/RegistryConfigDeclarer.java
  sermant-plugins/sermant-service-registry/dubbo-registry-plugin/src/main/java/com/huawei/dubbo/registry/interceptor/RegistryConfigInterceptor.java
  sermant-plugins/sermant-service-registry/dubbo-registry-plugin/src/main/java/com/huawei/dubbo/registry/utils/ReflectUtils.java
  sermant-plugins/sermant-service-registry/dubbo-registry-plugin/src/main/resources/META-INF/services/com.huawei.sermant.core.plugin.agent.declarer.PluginDeclarer
  sermant-plugins/sermant-service-registry/dubbo-registry-plugin/src/test/java/com/huawei/dubbo/registry/RegistryConfigInterceptorTest.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/service/RegistryConfigServiceImpl.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/test/java/com/huawei/dubbo/registry/RegistryConfigServiceTest.java
  sermant-plugins/sermant-service-registry/registry-common/src/main/java/com/huawei/registry/config/RegisterConfig.java
Labels: documentation, enhancement

#515 FAQ文档整改
  docs/FAQ.md
  docs/user-guide/FAQ.md
  docs/user-guide/flowcontrol/FAQ.md
  docs/user-guide/registry/FAQ.md
Labels: document

#526 checkstyle更改包名检查规则
  checkstyle.xml
Labels: enhancement

#528 【fix】修复config.properties中agent.config.ignoredPrefixes参数不生效的bug
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/config/strategy/LoadPropertiesStrategy.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/config/utils/ConfigValueUtil.java
Labels: bug

#531 【bug&feature】修复多版本生产者注册时，会存在消费者只能发现一个生产者实例的bug；增加对消费者下发配置的功能
  sermant-plugins/sermant-service-registry/dubbo-registry-plugin/src/main/java/com/huawei/dubbo/registry/declarer/RegistryProtocolDeclarer.java
  sermant-plugins/sermant-service-registry/dubbo-registry-plugin/src/main/java/com/huawei/dubbo/registry/service/RegistryService.java
  sermant-plugins/sermant-service-registry/dubbo-registry-plugin/src/test/java/com/huawei/dubbo/registry/ExtensionLoaderInterceptorTest.java
  sermant-plugins/sermant-service-registry/dubbo-registry-plugin/src/test/java/com/huawei/dubbo/registry/RegistryConfigInterceptorTest.java
  sermant-plugins/sermant-service-registry/dubbo-registry-plugin/src/test/java/com/huawei/dubbo/registry/RegistryFactoryTest.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/entity/GovernanceCache.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/entity/GovernanceData.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/entity/InterfaceData.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/entity/InterfaceKey.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/entity/ProviderInfo.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/entity/SchemaInfo.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/entity/Subscription.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/entity/SubscriptionKey.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/listener/GovernanceConfigListener.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/service/ApplicationConfigServiceImpl.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/service/GovernanceService.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/service/RegistryServiceImpl.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/resources/META-INF/services/com.huaweicloud.sermant.core.plugin.service.PluginService
  sermant-plugins/sermant-service-registry/registry-common/src/main/java/com/huawei/registry/config/RegisterConfig.java
Labels: bug, enhancement
