Repository sermant-io/Sermant, pull requests merged in 2022-05, with the labels that each got.

#539 【feature】增加对tag参数的支持
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/entity/InterfaceData.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/listener/GovernanceConfigListener.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/service/RegistryServiceImpl.java
  sermant-plugins/sermant-service-registry/registry-common/src/main/java/com/huawei/registry/config/RegisterConfig.java
Labels: enhancement

#540 【fix】修复双注册时因从sc查询不到实例导致无法调用的问题
  sermant-plugins/sermant-service-registry/spring-cloud-registry-service/src/main/java/com/huawei/registry/service/client/ScClient.java
Labels: bug

#543 【fix】修复流控与注册插件部分问题
  sermant-agentcore/sermant-agentcore-core/pom.xml
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/config/SpringEnvironmentInterceptor.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/interceptors/ServerListInterceptor.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/utils/MarkUtils.java
Labels: bug

#544 【fix】注册开关相关问题修复
  sermant-plugins/pom.xml
  sermant-plugins/sermant-dynamic-config/pom.xml
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/config/RegisterDynamicConfigSyncer.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/handler/SingleStateCloseHandler.java
Labels: bug

#545 【fix】流控路径匹配问题修复
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/DispatcherServletInterceptor.java
Labels: bug

#547 【fix】优化双注册时实例查询不到时的日志优化
  sermant-plugins/sermant-dynamic-config/dynamic-config-plugin/src/main/java/com/huawei/dynamic/config/interceptors/SpringEnvironmentInterceptor.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/config/SpringEnvironmentInterceptor.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/declarers/health/ZookeeperIndicatorDeclarer.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/handler/SingleStateCloseHandler.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/interceptors/health/ConsulHealthInterceptor.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/interceptors/health/EurekaHealthInterceptor.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/interceptors/health/NacosHealthInterceptor.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/interceptors/health/ZookeeperHealthInterceptor.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/interceptors/health/ZookeeperIndicatorInterceptor.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/support/RegisterSwitchSupport.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/resources/META-INF/services/com.huaweicloud.sermant.core.plugin.agent.declarer.PluginDeclarer
  sermant-plugins/sermant-service-registry/spring-cloud-registry-service/src/main/java/com/huawei/registry/service/client/ScClient.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-service/src/main/java/com/huawei/registry/service/client/ScDiscovery.java
Labels: bug

#549 【fix】兼容在alibaba dubbo在2.6.6-2.6.12版本区间其invocation的invoker为空的场景
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/AlibabaDubboInterceptor.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/ApacheDubboInterceptor.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/AlibabaDubboInvokerInterceptor.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/ApacheDubboInvokerInterceptor.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/service/InterceptorSupporter.java
Labels: bug

#552 【fix】流控黑名单逻辑修复
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/ApacheDubboInvokerInterceptor.java
Labels: bug

#551 【Feature】流水线增加集成测试
  .github/workflows/integration_test.yml
  .github/workflows/maven.yml
  pom.xml
  sermant-integration-tests/dubbo-test/dubbo-2-6-integration-consumer/pom.xml
  sermant-integration-tests/dubbo-test/dubbo-2-6-integration-consumer/src/main/java/com/huaweicloud/integration/ConsumerApplication.java
  sermant-integration-tests/dubbo-test/dubbo-2-6-integration-consumer/src/main/java/com/huaweicloud/integration/controller/ConsumerBarController.java
  sermant-integration-tests/dubbo-test/dubbo-2-6-integration-consumer/src/main/java/com/huaweicloud/integration/controller/ConsumerFooController.java
  sermant-integration-tests/dubbo-test/dubbo-2-6-integration-consumer/src/main/resources/application.yaml
  sermant-integration-tests/dubbo-test/dubbo-2-6-integration-consumer/src/main/resources/dubbo/consumer.xml
  sermant-integration-tests/dubbo-test/dubbo-2-6-integration-provider/pom.xml
  sermant-integration-tests/dubbo-test/dubbo-2-6-integration-provider/src/main/java/com/huaweicloud/integration/ProviderApplication.java
  sermant-integration-tests/dubbo-test/dubbo-2-6-integration-provider/src/main/java/com/huaweicloud/integration/service/Bar2ServiceImpl.java
  sermant-integration-tests/dubbo-test/dubbo-2-6-integration-provider/src/main/java/com/huaweicloud/integration/service/BarServiceImpl.java
  sermant-integration-tests/dubbo-test/dubbo-2-6-integration-provider/src/main/java/com/huaweicloud/integration/service/FooServiceImpl.java
  sermant-integration-tests/dubbo-test/dubbo-2-6-integration-provider/src/main/resources/application.yaml
  sermant-integration-tests/dubbo-test/dubbo-2-6-integration-provider/src/main/resources/dubbo/provider.xml
  sermant-integration-tests/dubbo-test/dubbo-2-7-integration-consumer/pom.xml
  sermant-integration-tests/dubbo-test/dubbo-2-7-integration-consumer/src/main/java/com/huaweicloud/integration/ConsumerApplication.java
  sermant-integration-tests/dubbo-test/dubbo-2-7-integration-consumer/src/main/java/com/huaweicloud/integration/controller/ConsumerBarController.java
  sermant-integration-tests/dubbo-test/dubbo-2-7-integration-consumer/src/main/java/com/huaweicloud/integration/controller/ConsumerFooController.java
  sermant-integration-tests/dubbo-test/dubbo-2-7-integration-consumer/src/main/resources/application.yaml
  sermant-integration-tests/dubbo-test/dubbo-2-7-integration-consumer/src/main/resources/dubbo/consumer.xml
  sermant-integration-tests/dubbo-test/dubbo-2-7-integration-provider/pom.xml
  sermant-integration-tests/dubbo-test/dubbo-2-7-integration-provider/src/main/java/com/huaweicloud/integration/ProviderApplication.java
  sermant-integration-tests/dubbo-test/dubbo-2-7-integration-provider/src/main/java/com/huaweicloud/integration/service/Bar2ServiceImpl.java
  sermant-integration-tests/dubbo-test/dubbo-2-7-integration-provider/src/main/java/com/huaweicloud/integration/service/BarServiceImpl.java
  sermant-integration-tests/dubbo-test/dubbo-2-7-integration-provider/src/main/java/com/huaweicloud/integration/service/FooServiceImpl.java
  sermant-integration-tests/dubbo-test/dubbo-2-7-integration-provider/src/main/resources/application.yaml
  sermant-integration-tests/dubbo-test/dubbo-2-7-integration-provider/src/main/resources/dubbo/provider.xml
  sermant-integration-tests/dubbo-test/dubbo-integration-api/pom.xml
  sermant-integration-tests/dubbo-test/dubbo-integration-api/src/main/java/com/huaweicloud/integration/service/BarService.java
  sermant-integration-tests/dubbo-test/dubbo-integration-api/src/main/java/com/huaweicloud/integration/service/ConsumerBarService.java
  sermant-integration-tests/dubbo-test/dubbo-integration-api/src/main/java/com/huaweicloud/integration/service/ConsumerFooService.java
  sermant-integration-tests/dubbo-test/dubbo-integration-api/src/main/java/com/huaweicloud/integration/service/FooService.java
  sermant-integration-tests/dubbo-test/dubbo-integration-test/pom.xml
  sermant-integration-tests/dubbo-test/dubbo-integration-test/src/test/java/com/huaweicloud/integration/ConsumerTest.java
  sermant-integration-tests/dubbo-test/pom.xml
  sermant-integration-tests/pom.xml
Labels: feature

#559 【fix】修改ReadMe和插件模块开发手册中与现有工程不符合的部分
  docs/README.md
  docs/dev-guide/dev_plugin_module.md
Labels: bug, document

#560 【fix】修正SpringCloud注册框架为Sermant
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/service/RegistryServiceImpl.java
  sermant-plugins/sermant-service-registry/registry-common/src/main/java/com/huawei/registry/config/ConfigConstants.java
  sermant-plugins/sermant-service-registry/registry-common/src/main/java/com/huawei/registry/config/RegisterConfig.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-service/src/main/java/com/huawei/registry/service/client/ScClient.java
Labels: bug
