Repository sermant-io/Sermant, pull requests merged in 2022-07, with the labels that each got.

#577 【document】验收demo相关测试问题修改
  sermant-example/demo-grace/spring-grace-nacos-demo/deploy/config.sh
  sermant-example/demo-grace/spring-grace-nacos-demo/deploy/graceDown/provider-closeGraceDown.yaml
  sermant-example/demo-grace/spring-grace-nacos-demo/deploy/invoke-hot.sh
  sermant-example/demo-grace/spring-grace-nacos-demo/deploy/invoke.sh
  sermant-example/demo-grace/spring-grace-nacos-demo/deploy/stat.sh
  sermant-example/demo-grace/spring-grace-nacos-demo/nacos-rest-consumer/src/main/resources/application.yml
Labels: documentation

#578 【document】补充优雅上下线UT
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/pom.xml
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/test/java/com/huawei/registry/config/RegistryConfigResolverTest.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/test/java/com/huawei/registry/grace/interceptors/RegistryDelayInterceptorTest.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/test/java/com/huawei/registry/grace/interceptors/ResponseTest.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/test/java/com/huawei/registry/grace/interceptors/SpringCacheManagerInterceptorTest.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/test/java/com/huawei/registry/grace/interceptors/SpringLoadbalancerFeignResponseInterceptorTest.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/test/java/com/huawei/registry/grace/interceptors/SpringLoadbalancerRestTemplateResponseInterceptorTest.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/test/java/com/huawei/registry/grace/interceptors/SpringLoadbalancerWarmUpInterceptorTest.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/test/java/com/huawei/registry/grace/interceptors/SpringRibbonWarmUpInterceptorTest.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/test/java/com/huawei/registry/grace/interceptors/SpringWebHandlerInterceptorTest.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/test/java/com/huawei/registry/grace/interceptors/SpringZuulResponseInterceptorTest.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/test/java/com/huawei/registry/grace/interceptors/WarmUpTest.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/test/java/com/huawei/registry/interceptors/SpringFactoriesInterceptorTest.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/test/java/com/huawei/registry/utils/CommonUtilsTest.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/test/java/com/huawei/registry/utils/ReflectUtilsTest.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/test/java/com/huawei/registry/utils/ZoneUtilsTest.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-service/pom.xml
  sermant-plugins/sermant-service-registry/spring-cloud-registry-service/src/test/java/com/huawei/registry/service/cache/AddressCacheTest.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-service/src/test/java/com/huawei/registry/service/client/ScDiscoveryTest.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-service/src/test/java/com/huawei/registry/service/impl/GraceServiceImplTest.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-service/src/test/java/com/huawei/registry/service/server/GraceHttpServerTest.java
Labels: document

#582 【fix】修护环境变量和启动参数可能存在的优先级读取错误问题
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/config/utils/ConfigValueUtil.java
Labels: bug

#591 【fix】修改feature-list文档
  docs/user-guide/feature-list.md
  docs/user-guide/registry/dubbo-registry-migiration.md
  docs/user-guide/registry/spring-cloud-registry-migiration.md
Labels: document

#593 更改失效文档链接
  README.md
  docs/dev-guide/dev_plugin_code.md
Labels: documentation

#600 【BUG】删除日志模版颜色渲染
  sermant-agentcore/sermant-agentcore-config/config/logback.xml
Labels: bug

#602 【Feature】增加spring标签路由demo
  sermant-plugins/sermant-router/router-demo/pom.xml
  sermant-plugins/sermant-router/router-demo/spring-router-demo/consumer-demo/pom.xml
  sermant-plugins/sermant-router/router-demo/spring-router-demo/consumer-demo/src/main/java/com/huaweicloud/router/spring/demo/ConsumerApplication.java
  sermant-plugins/sermant-router/router-demo/spring-router-demo/consumer-demo/src/main/java/com/huaweicloud/router/spring/demo/client/ProviderClient.java
  sermant-plugins/sermant-router/router-demo/spring-router-demo/consumer-demo/src/main/java/com/huaweicloud/router/spring/demo/controller/ConsumerController.java
  sermant-plugins/sermant-router/router-demo/spring-router-demo/consumer-demo/src/main/resources/application.yml
  sermant-plugins/sermant-router/router-demo/spring-router-demo/pom.xml
  sermant-plugins/sermant-router/router-demo/spring-router-demo/provider-demo/pom.xml
  sermant-plugins/sermant-router/router-demo/spring-router-demo/provider-demo/src/main/java/com/huaweicloud/router/spring/demo/ProviderApplication.java
  sermant-plugins/sermant-router/router-demo/spring-router-demo/provider-demo/src/main/java/com/huaweicloud/router/spring/demo/controller/ProviderController.java
  sermant-plugins/sermant-router/router-demo/spring-router-demo/provider-demo/src/main/resources/application.yml
  sermant-plugins/sermant-router/router-demo/spring-router-demo/zuul-demo/pom.xml
  sermant-plugins/sermant-router/router-demo/spring-router-demo/zuul-demo/src/main/java/com/huaweicloud/router/spring/demo/ZuulApplication.java
  sermant-plugins/sermant-router/router-demo/spring-router-demo/zuul-demo/src/main/resources/application.yml
  sermant-plugins/sermant-router/router-demo/spring-router-demo/zuul-demo/src/test/java/com/huaweicloud/router/spring/demo/RouterTest.java
Labels: feature

#598 【feature】插件加载增加场景参数配置，支持通过-D指定场景名
  sermant-agentcore/sermant-agentcore-config/config/all/plugins.yaml
  sermant-agentcore/sermant-agentcore-config/config/plugins.yaml
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/common/CommonConstant.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/config/utils/ConfigValueUtil.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/plugin/PluginSystemEntrance.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/plugin/config/PluginSetting.java
Labels: feature

#605 【fix】修复监听KIE配置时，无法监听env为空的配置
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/service/dynamicconfig/utils/LabelGroupUtils.java
Labels: bug

#607 【fix】增加以IP地址替换域名的访问配置
  sermant-plugins/sermant-service-registry/config/config.yaml
  sermant-plugins/sermant-service-registry/registry-common/src/main/java/com/huawei/registry/config/RegisterConfig.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-service/src/main/java/com/huawei/registry/service/register/ServicecombServiceInstance.java
Labels: bug

#608 【fix】流控增加上游服务传递，用于判断服务端治理策略
  sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/config/ConfigConst.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/DispatcherServletInterceptor.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/FeignRequestInterceptor.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/HttpRequestInterceptor.java
Labels: bug

#611 【fix】修正流控部分bug
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/FeignRequestInterceptor.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/java/com/huawei/fowcontrol/res4j/chain/HandlerConstants.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/java/com/huawei/fowcontrol/res4j/chain/handler/CircuitBreakerRequestHandler.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/resources/META-INF/services/com.huawei.fowcontrol.res4j.chain.AbstractChainHandler
Labels: bug
