Repository sermant-io/Sermant, pull requests merged in 2022-08, with the labels that each got.

#614 【Feature】增加spring标签路由demo的部署文件
  checkstyle.xml
  sermant-plugins/sermant-router/router-demo/spring-router-demo/deployment/images/consumer/Dockerfile
  sermant-plugins/sermant-router/router-demo/spring-router-demo/deployment/images/consumer/build.sh
  sermant-plugins/sermant-router/router-demo/spring-router-demo/deployment/images/consumer/start.sh
  sermant-plugins/sermant-router/router-demo/spring-router-demo/deployment/images/provider/Dockerfile
  sermant-plugins/sermant-router/router-demo/spring-router-demo/deployment/images/provider/build.sh
  sermant-plugins/sermant-router/router-demo/spring-router-demo/deployment/images/provider/start.sh
  sermant-plugins/sermant-router/router-demo/spring-router-demo/deployment/images/zuul/Dockerfile
  sermant-plugins/sermant-router/router-demo/spring-router-demo/deployment/images/zuul/build.sh
  sermant-plugins/sermant-router/router-demo/spring-router-demo/deployment/images/zuul/start.sh
  sermant-plugins/sermant-router/router-demo/spring-router-demo/deployment/k8s/consumer.yaml
  sermant-plugins/sermant-router/router-demo/spring-router-demo/deployment/k8s/gray-provider.yaml
  sermant-plugins/sermant-router/router-demo/spring-router-demo/deployment/k8s/provider.yaml
  sermant-plugins/sermant-router/router-demo/spring-router-demo/deployment/k8s/zuul.yaml
  sermant-plugins/sermant-router/router-demo/spring-router-demo/provider-demo/pom.xml
  sermant-plugins/sermant-router/router-demo/spring-router-demo/provider-demo/src/main/java/com/huaweicloud/router/spring/demo/ProviderApplication.java
Labels: feature

#616 【fix】restemplate重试修复
  sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/adapte/cse/RuleUtils.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/inject/FlowControlSpringConfigurationInjectDefine.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/inject/RetryClientHttpResponse.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/inject/retry/RetryInjectDefine.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/inject/retry/RetryableRestTemplate.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/inject/retry/SpringRetryConfiguration.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/FeignRequestInterceptor.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/HttpRequestInterceptor.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/handler/RetryHandlerV2.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/service/InterceptorSupporter.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/resources/META-INF/services/com.huaweicloud.sermant.core.plugin.inject.ClassInjectDefine
Labels: bug

#613 增加插件去源码开发说明
  docs/README.md
  docs/dev-guide/Sermant去源码插件开发说明.md
Labels: document

#625 【feature】新增sermant-injector组件实现容器化部署自动挂载javaagent
  pom.xml
  sermant-injector/deployment/release/injector_k8s_1.19+/Chart.yaml
  sermant-injector/deployment/release/injector_k8s_1.19+/templates/sermant-injector-configmap.yaml
  sermant-injector/deployment/release/injector_k8s_1.19+/templates/sermant-injector-deployment.yaml
  sermant-injector/deployment/release/injector_k8s_1.19+/templates/sermant-injector-service.yaml
  sermant-injector/deployment/release/injector_k8s_1.19+/templates/sermant-injector-webhook.yaml
  sermant-injector/deployment/release/injector_k8s_1.19+/values.yaml
  sermant-injector/deployment/release/injector_k8s_1.21-/Chart.yaml
  sermant-injector/deployment/release/injector_k8s_1.21-/templates/sermant-injector-configmap.yaml
  sermant-injector/deployment/release/injector_k8s_1.21-/templates/sermant-injector-deployment.yaml
  sermant-injector/deployment/release/injector_k8s_1.21-/templates/sermant-injector-service.yaml
  sermant-injector/deployment/release/injector_k8s_1.21-/templates/sermant-injector-webhook.yaml
  sermant-injector/deployment/release/injector_k8s_1.21-/values.yaml
  sermant-injector/images/injector/Injector.Dockerfile
  sermant-injector/images/injector/build-injector-image.sh
  sermant-injector/images/injector/start.sh
  sermant-injector/images/sermant-agent/Sermant.Dockerfile
  sermant-injector/images/sermant-agent/build-sermant-image.sh
  sermant-injector/pom.xml
  sermant-injector/scripts/certificate_k8s_1.19+/certificate.sh
  sermant-injector/scripts/certificate_k8s_1.21-/certificate.sh
  sermant-injector/src/main/java/com/huaweicloud/sermant/injection/InjectorApplication.java
  sermant-injector/src/main/java/com/huaweicloud/sermant/injection/certificate/CertificateEnvironmentPostProcessor.java
  sermant-injector/src/main/java/com/huaweicloud/sermant/injection/controller/SermantInjectionController.java
  sermant-injector/src/main/java/com/huaweicloud/sermant/injection/dto/Response.java
  sermant-injector/src/main/java/com/huaweicloud/sermant/injection/dto/WebhookResponse.java
  sermant-injector/src/main/java/com/huaweicloud/sermant/injection/listener/AvailabilityListener.java
  sermant-injector/src/main/resources/META-INF/spring.factories
  sermant-injector/src/main/resources/application.yml
  sermant-injector/src/test/java/com/huaweicloud/sermant/injection/controller/SermantInjectionControllerTest.java
  sermant-injector/src/test/resources/test.json
Labels: feature

#618 【feature】流控demo提交
  sermant-example/demo-flowcontrol/pom.xml
  sermant-example/demo-flowcontrol/spring-rest-consumer/pom.xml
  sermant-example/demo-flowcontrol/spring-rest-consumer/src/main/java/com/huaweicloud/flowcontrol/rest/consumer/FlowRestController.java
  sermant-example/demo-flowcontrol/spring-rest-consumer/src/main/java/com/huaweicloud/flowcontrol/rest/consumer/RestConsumerApplication.java
  sermant-example/demo-flowcontrol/spring-rest-consumer/src/main/resources/application.yml
  sermant-example/demo-flowcontrol/spring-rest-provider/pom.xml
  sermant-example/demo-flowcontrol/spring-rest-provider/src/main/java/com/huaweicloud/flowcontrol/rest/provider/FlowRestController.java
  sermant-example/demo-flowcontrol/spring-rest-provider/src/main/java/com/huaweicloud/flowcontrol/rest/provider/RestProviderApplication.java
  sermant-example/demo-flowcontrol/spring-rest-provider/src/main/resources/application.yaml
  sermant-example/pom.xml
Labels: enhancement

#633 【document】容器化部署宿主应用自动挂载sermant-agent指导手册
  docs/README.md
  docs/user-guide/injector.md
Labels: document

#634 【fix】修复熔断请求次数统计过多问题, 区分异常与结果, 分别统计
  sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/entity/FlowControlResult.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/enums/FlowControlEnum.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/java/com/huawei/fowcontrol/res4j/chain/HandlerChainEntry.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/java/com/huawei/fowcontrol/res4j/chain/HandlerConstants.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/java/com/huawei/fowcontrol/res4j/chain/handler/BulkheadRequestHandler.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/java/com/huawei/fowcontrol/res4j/chain/handler/CircuitBreakerRequestHandler.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/resources/META-INF/services/com.huawei.fowcontrol.res4j.chain.AbstractChainHandler
Labels: bug

#637 【document】去除无用测试数据
  sermant-injector/src/test/resources/test.json
Labels: document

#640 【bug】修复删除命名空间后证书失效的问题
  sermant-injector/scripts/certificate_k8s_1.19+/certificate.sh
  sermant-injector/scripts/certificate_k8s_1.21-/certificate.sh
Labels: bug

#639 【bug】修复加载某个插件过程发生异常导致整个agent启动失败的问题
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/plugin/PluginManager.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/plugin/adaptor/AdaptorManager.java
Labels: bug

#645 插件去源码开发文档修改
  docs/dev-guide/Sermant去源码插件开发说明.md
Labels: document

#643 【BUG】backend模块指定repackage版本
  sermant-backend/pom.xml
Labels: bug

#641 【bug】修复profile包含空格以及profile可能为null的问题
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/plugin/PluginManager.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/plugin/PluginSystemEntrance.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/plugin/config/PluginSetting.java
Labels: bug

#636 【Feature】修改标签路由功能解析配置的方式
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/plugin/subscribe/processor/ConfigOrderIntegratedProcessor.java
  sermant-plugins/sermant-router/router-common/src/main/java/com/huaweicloud/sermant/router/common/constants/RouterConstant.java
  sermant-plugins/sermant-router/router-config-common/src/main/java/com/huaweicloud/sermant/router/config/label/entity/RouterConfiguration.java
  sermant-plugins/sermant-router/router-config-common/src/main/java/com/huaweicloud/sermant/router/config/utils/RuleUtils.java
  sermant-plugins/sermant-router/router-config-common/src/test/java/com/huaweicloud/sermant/router/config/utils/RuleUtilsTest.java
  sermant-plugins/sermant-router/router-config-service/src/main/java/com/huaweicloud/sermant/router/config/handler/AbstractConfigHandler.java
  sermant-plugins/sermant-router/router-config-service/src/main/java/com/huaweicloud/sermant/router/config/handler/RouterConfigHandler.java
  sermant-plugins/sermant-router/router-config-service/src/main/java/com/huaweicloud/sermant/router/config/handler/ServiceConfigHandler.java
  sermant-plugins/sermant-router/router-config-service/src/main/java/com/huaweicloud/sermant/router/config/listener/RouterConfigListener.java
Labels: enhancement

#658 【feature】优化properties和config.yaml配置文件驼峰和中划线支持以及相应环境变量读取
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/config/strategy/LoadYamlStrategy.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/config/utils/ConfigValueUtil.java
  sermant-example/demo-plugin/src/main/java/com/huawei/example/demo/config/DemoConfig.java
Labels: feature

#654 【Feature】优化注册插件
  .github/workflows/integration_test.yml
  .gitignore
  sermant-integration-tests/dubbo-test/dubbo-2-6-integration-consumer/src/main/java/com/huaweicloud/integration/ConsumerApplication.java
  sermant-integration-tests/dubbo-test/dubbo-2-6-integration-consumer/src/main/java/com/huaweicloud/integration/controller/ConsumerFooWildcardController.java
  sermant-integration-tests/dubbo-test/dubbo-2-6-integration-consumer/src/main/resources/application.yaml
  sermant-integration-tests/dubbo-test/dubbo-2-6-integration-consumer/src/main/resources/dubbo/consumer.xml
  sermant-integration-tests/dubbo-test/dubbo-2-6-integration-provider/src/main/java/com/huaweicloud/integration/ProviderApplication.java
  sermant-integration-tests/dubbo-test/dubbo-2-6-integration-provider/src/main/resources/application.yaml
  sermant-integration-tests/dubbo-test/dubbo-2-7-integration-consumer/src/main/java/com/huaweicloud/integration/ConsumerApplication.java
  sermant-integration-tests/dubbo-test/dubbo-2-7-integration-consumer/src/main/java/com/huaweicloud/integration/controller/ConsumerFooWildcardController.java
  sermant-integration-tests/dubbo-test/dubbo-2-7-integration-consumer/src/main/resources/application.yaml
  sermant-integration-tests/dubbo-test/dubbo-2-7-integration-consumer/src/main/resources/dubbo/consumer.xml
  sermant-integration-tests/dubbo-test/dubbo-2-7-integration-provider/src/main/java/com/huaweicloud/integration/ProviderApplication.java
  sermant-integration-tests/dubbo-test/dubbo-2-7-integration-provider/src/main/resources/application.yaml
  sermant-integration-tests/dubbo-test/dubbo-integration-api/pom.xml
  sermant-integration-tests/dubbo-test/dubbo-integration-api/src/main/java/com/huaweicloud/integration/client/ProviderClient.java
  sermant-integration-tests/dubbo-test/dubbo-integration-api/src/main/java/com/huaweicloud/integration/controller/ConsumerController.java
  sermant-integration-tests/dubbo-test/dubbo-integration-api/src/main/java/com/huaweicloud/integration/controller/ProviderController.java
  sermant-integration-tests/dubbo-test/dubbo-integration-test/src/test/java/com/huaweicloud/integration/ConsumerTest.java
  sermant-integration-tests/dubbo-test/dubbo-integration-test/src/test/java/com/huaweicloud/integration/SpringAndDubboTest.java
  sermant-integration-tests/dubbo-test/pom.xml
  sermant-plugins/sermant-router/spring-router-plugin/src/main/java/com/huaweicloud/sermant/router/spring/interceptor/EurekaHttpClientInterceptor.java
  sermant-plugins/sermant-router/spring-router-plugin/src/main/java/com/huaweicloud/sermant/router/spring/interceptor/ServiceInstanceListSupplierInterceptor.java
  sermant-plugins/sermant-router/spring-router-plugin/src/main/java/com/huaweicloud/sermant/router/spring/interceptor/ServiceRegistryInterceptor.java
  sermant-plugins/sermant-router/spring-router-plugin/src/main/java/com/huaweicloud/sermant/router/spring/utils/SpringRouterUtils.java
  sermant-plugins/sermant-router/spring-router-service/src/main/java/com/huaweicloud/sermant/router/spring/strategy/instance/MismatchInstanceStrategy.java
  sermant-plugins/sermant-router/spring-router-service/src/main/java/com/huaweicloud/sermant/router/spring/strategy/instance/TargetInstanceStrategy.java
  sermant-plugins/sermant-router/spring-router-service/src/main/java/com/huaweicloud/sermant/router/spring/strategy/rule/DefaultRuleStrategy.java
  sermant-plugins/sermant-router/spring-router-service/src/main/java/com/huaweicloud/sermant/router/spring/strategy/rule/EurekaRuleStrategy.java
  sermant-plugins/sermant-router/spring-router-service/src/main/java/com/huaweicloud/sermant/router/spring/strategy/rule/ZookeeperRuleStrategy.java
  sermant-plugins/sermant-service-registry/dubbo-registry-plugin/src/main/java/com/huawei/dubbo/registry/interceptor/ExtensionLoaderInterceptor.java
  sermant-plugins/sermant-service-registry/dubbo-registry-plugin/src/main/java/com/huawei/dubbo/registry/utils/ReflectUtils.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/pom.xml
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/entity/InterfaceData.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/entity/InterfaceKey.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/entity/SubscriptionKey.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/service/RegistryServiceImpl.java
  sermant-plugins/sermant-service-registry/pom.xml
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/auto/sc/configuration/ServiceCombAutoDiscoveryConfiguration.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-service/pom.xml
  sermant-plugins/sermant-service-registry/spring-cloud-registry-service/src/main/java/com/huawei/registry/service/client/ScClient.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-service/src/main/java/com/huawei/registry/service/register/ScRegister.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-service/src/main/java/com/huawei/registry/service/register/ServicecombServiceInstance.java
Labels: enhancement

#652 灰度插件支持dubbo attachment参数
  sermant-plugins/sermant-router/dubbo-router-plugin/src/main/java/com/huaweicloud/sermant/router/dubbo/declarer/RegistrationDeclarer.java
  sermant-plugins/sermant-router/dubbo-router-plugin/src/main/java/com/huaweicloud/sermant/router/dubbo/interceptor/RegistrationInterceptor.java
  sermant-plugins/sermant-router/dubbo-router-plugin/src/main/java/com/huaweicloud/sermant/router/dubbo/service/RegistrationService.java
  sermant-plugins/sermant-router/dubbo-router-plugin/src/main/java/com/huaweicloud/sermant/router/dubbo/utils/DubboReflectUtils.java
  sermant-plugins/sermant-router/dubbo-router-plugin/src/main/resources/META-INF/services/com.huaweicloud.sermant.core.plugin.agent.declarer.PluginDeclarer
  sermant-plugins/sermant-router/dubbo-router-plugin/src/test/java/com/huaweicloud/sermant/router/dubbo/RegistrationInterceptorTest.java
  sermant-plugins/sermant-router/dubbo-router-service/src/main/java/com/huaweicloud/sermant/router/dubbo/service/AbstractDirectoryServiceImpl.java
  sermant-plugins/sermant-router/dubbo-router-service/src/main/java/com/huaweicloud/sermant/router/dubbo/service/ApplicationConfigServiceImpl.java
  sermant-plugins/sermant-router/dubbo-router-service/src/main/java/com/huaweicloud/sermant/router/dubbo/service/ClusterServiceImpl.java
  sermant-plugins/sermant-router/dubbo-router-service/src/main/java/com/huaweicloud/sermant/router/dubbo/service/RegistrationServiceImpl.java
  sermant-plugins/sermant-router/dubbo-router-service/src/main/java/com/huaweicloud/sermant/router/dubbo/strategy/RuleStrategyHandler.java
  sermant-plugins/sermant-router/dubbo-router-service/src/main/java/com/huaweicloud/sermant/router/dubbo/strategy/instance/MismatchInstanceStrategy.java
  sermant-plugins/sermant-router/dubbo-router-service/src/main/java/com/huaweicloud/sermant/router/dubbo/strategy/instance/TargetInstanceStrategy.java
  sermant-plugins/sermant-router/dubbo-router-service/src/main/java/com/huaweicloud/sermant/router/dubbo/utils/RouteUtils.java
  sermant-plugins/sermant-router/dubbo-router-service/src/main/resources/META-INF/services/com.huaweicloud.sermant.core.plugin.service.PluginService
  sermant-plugins/sermant-router/dubbo-router-service/src/test/java/com/huaweicloud/sermant/router/dubbo/service/ApplicationConfigServiceTest.java
  sermant-plugins/sermant-router/dubbo-router-service/src/test/java/com/huaweicloud/sermant/router/dubbo/service/ClusterServiceTest.java
  sermant-plugins/sermant-router/router-common/src/main/java/com/huaweicloud/sermant/router/common/config/RouterConfig.java
  sermant-plugins/sermant-router/router-common/src/main/java/com/huaweicloud/sermant/router/common/constants/RouterConstant.java
  sermant-plugins/sermant-router/router-common/src/main/java/com/huaweicloud/sermant/router/common/utils/ReflectUtils.java
  sermant-plugins/sermant-router/router-config-common/src/main/java/com/huaweicloud/sermant/router/config/label/entity/CurrentTag.java
  sermant-plugins/sermant-router/router-config-common/src/main/java/com/huaweicloud/sermant/router/config/label/entity/Match.java
  sermant-plugins/sermant-router/router-config-common/src/main/java/com/huaweicloud/sermant/router/config/label/entity/RouterConfiguration.java
  sermant-plugins/sermant-router/router-config-common/src/main/java/com/huaweicloud/sermant/router/config/utils/RuleUtils.java
  sermant-plugins/sermant-router/router-config-service/src/main/java/com/huaweicloud/sermant/router/config/handler/ServiceConfigHandler.java
Labels: feature

#657 【feature】适配declarer的开关，优化双注册去重逻辑
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/config/RegistrationProperties.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/declarers/AbstractBaseConfigDeclarer.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/declarers/AbstractDoubleRegistryDeclarer.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/declarers/DiscoveryClientConfigurationDeclarer.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/declarers/DiscoveryClientDeclarer.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/declarers/DynamicServerListLoadbalancerDeclarer.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/declarers/cloud3/x/ZookeeperInstanceSupplierDeclarer.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/declarers/health/ConsulHealthDeclarer.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/declarers/health/ConsulWatchConDeclarer.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/declarers/health/EurekaHealthDeclarer.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/declarers/health/HealthIndicatorDeclarer.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/declarers/health/NacosHealthDeclarer.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/declarers/health/ScheduleProcessorDeclared.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/declarers/health/ZookeeperHealthDeclarer.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/interceptors/DiscoveryClientInterceptor.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/interceptors/DynamicServerListInterceptor.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/utils/HostUtils.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-service/src/main/java/com/huawei/registry/service/client/ScClient.java
Labels: enhancement

#661 【fix】修复注册在未就绪的情况下查询服务名报错的问题
  sermant-plugins/sermant-service-registry/spring-cloud-registry-service/src/main/java/com/huawei/registry/service/impl/RegisterCenterServiceImpl.java
Labels: bug

#663 【fix】修复基于配置中心下发优雅上下线开关存在类找不到的问题
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/inject/ContextClosedEventListenerInjectDefine.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/inject/RequestInterceptorInjectDefine.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/inject/grace/ContextClosedEventListener.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/inject/grace/SpringRequestInterceptor.java
Labels: bug

#660 【fix】修复properties和yaml配置文件缺省key时环境变量配置值不生效的问题
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/config/strategy/LoadPropertiesStrategy.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/config/strategy/LoadYamlStrategy.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/config/utils/ConfigValueUtil.java
Labels: bug

#659 【doc】流控文档与负载均衡文档修改
  docs/user-guide/flowcontrol/flowcontrol.md
  docs/user-guide/loadbalancer/document.md
Labels: documentation

#668 【doc】更新插件配置文件相关文档
  docs/dev-guide/dev_plugin_code.md
Labels: document

#672 【fix】修复dubbo注册时，有可能触发空指针的bug
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/service/RegistryServiceImpl.java
Labels: bug

#667 增加注册监控插件
  pom.xml
  sermant-agentcore/sermant-agentcore-config/config/config.properties
  sermant-agentcore/sermant-agentcore-config/config/plugins.yaml
  sermant-agentcore/sermant-agentcore-core/pom.xml
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/service/monitor/MetricService.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/service/monitor/config/MonitorConfig.java
  sermant-agentcore/sermant-agentcore-core/src/main/resources/META-INF/services/com.huaweicloud.sermant.core.config.common.BaseConfig
  sermant-agentcore/sermant-agentcore-core/src/main/resources/META-INF/services/com.huaweicloud.sermant.core.service.BaseService
  sermant-agentcore/sermant-agentcore-core/src/test/java/com/huaweicloud/sermant/core/service/monitor/MetricServiceTest.java
  sermant-plugins/pom.xml
  sermant-plugins/sermant-monitor/monitor-service/pom.xml
  sermant-plugins/sermant-monitor/monitor-service/src/main/java/com/huawei/monitor/command/Command.java
  sermant-plugins/sermant-monitor/monitor-service/src/main/java/com/huawei/monitor/command/CommandExecutor.java
  sermant-plugins/sermant-monitor/monitor-service/src/main/java/com/huawei/monitor/command/CommonMonitorCommand.java
  sermant-plugins/sermant-monitor/monitor-service/src/main/java/com/huawei/monitor/command/CpuCommand.java
  sermant-plugins/sermant-monitor/monitor-service/src/main/java/com/huawei/monitor/command/CpuInfoCommand.java
  sermant-plugins/sermant-monitor/monitor-service/src/main/java/com/huawei/monitor/command/DiskCommand.java
  sermant-plugins/sermant-monitor/monitor-service/src/main/java/com/huawei/monitor/command/MemoryCommand.java
  sermant-plugins/sermant-monitor/monitor-service/src/main/java/com/huawei/monitor/command/MonitorCommand.java
  sermant-plugins/sermant-monitor/monitor-service/src/main/java/com/huawei/monitor/command/NetworkCommand.java
  sermant-plugins/sermant-monitor/monitor-service/src/main/java/com/huawei/monitor/common/Constants.java
  sermant-plugins/sermant-monitor/monitor-service/src/main/java/com/huawei/monitor/common/MemoryType.java
  sermant-plugins/sermant-monitor/monitor-service/src/main/java/com/huawei/monitor/common/MetricEnum.java
  sermant-plugins/sermant-monitor/monitor-service/src/main/java/com/huawei/monitor/common/MetricFamilyBuild.java
  sermant-plugins/sermant-monitor/monitor-service/src/main/java/com/huawei/monitor/service/JvmCollectorService.java
  sermant-plugins/sermant-monitor/monitor-service/src/main/java/com/huawei/monitor/service/ServerCollectorService.java
  sermant-plugins/sermant-monitor/monitor-service/src/main/java/com/huawei/monitor/util/CollectionUtil.java
  sermant-plugins/sermant-monitor/monitor-service/src/main/resources/META-INF/services/com.huaweicloud.sermant.core.plugin.service.PluginService
  sermant-plugins/sermant-monitor/monitor-service/src/test/java/com/huawei/monitor/CollectorServiceTest.java
  sermant-plugins/sermant-monitor/pom.xml
Labels: feature

#679 【feature】针对spring自动化测试增加测试错误时的日志上传
  .github/workflows/intergration_spring_test.yml
  sermant-agentcore/sermant-agentcore-config/config/logback.xml
Labels: feature

#681 【fix】修复yaml配置中boolean字段未配置时获取其他数据源参考值的解析问题
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/config/strategy/LoadYamlStrategy.java
Labels: bug

#678 【fix】修复关闭jvm时某个服务执行stop方法出现异常后续服务无法按预期关闭的问题
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/service/ServiceManager.java
Labels: bug

#683 【fix】修复熔断时间窗口时间单位问题
  sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/java/com/huawei/fowcontrol/res4j/handler/CircuitBreakerHandler.java
Labels: bug

#686 【fix】修复路由插件的bug
  sermant-plugins/sermant-router/dubbo-router-service/src/main/java/com/huaweicloud/sermant/router/dubbo/strategy/instance/MismatchInstanceStrategy.java
  sermant-plugins/sermant-router/router-config-common/src/main/java/com/huaweicloud/sermant/router/config/label/entity/RouterConfiguration.java
  sermant-plugins/sermant-router/router-config-common/src/main/java/com/huaweicloud/sermant/router/config/label/entity/ValueMatchDeserializer.java
  sermant-plugins/sermant-router/router-config-common/src/main/java/com/huaweicloud/sermant/router/config/utils/RuleUtils.java
Labels: bug

#687 【fix】修复dubbo应用开启spring注册出现类找不到的问题
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/config/RegistrationProperties.java
Labels: bug

#690 【fix】修复netty一直重连的bug
  sermant-agentcore/sermant-agentcore-config/config/all/config.properties
  sermant-agentcore/sermant-agentcore-config/config/config.properties
  sermant-agentcore/sermant-agentcore-config/config/example/config.properties
  sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/config/FlowControlConfig.java
  sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/enums/MetricSendWay.java
Labels: bug

#676 增加backend发布中心仓
  pom.xml
  sermant-backend/pom.xml
Labels: feature

#675 【doc】插件interceptor和service单元测试模版
  sermant-example/demo-plugin/pom.xml
  sermant-example/demo-plugin/src/main/java/com/huawei/example/demo/service/DemoSimpleService.java
  sermant-example/demo-plugin/src/test/java/com/huawei/example/demo/interceptor/DemoInterceptorTest.java
  sermant-example/demo-plugin/src/test/java/com/huawei/example/demo/service/DemoServiceTest.java
Labels: document

#693 【fix】修正并添加负载均衡插件UT
  sermant-plugins/sermant-loadbalancer/dubbo-loadbalancer-plugin/src/test/java/com/huaweicloud/loadbalancer/UrlInterceptorTest.java
  sermant-plugins/sermant-loadbalancer/dubbo-loadbalancer-plugin/src/test/java/com/huaweicloud/loadbalancer/cache/DubboLoadbalancerCacheTest.java
  sermant-plugins/sermant-loadbalancer/dubbo-loadbalancer-plugin/src/test/java/com/huaweicloud/loadbalancer/cache/RuleManagerHelper.java
  sermant-plugins/sermant-loadbalancer/loadbalancer-service/pom.xml
  sermant-plugins/sermant-loadbalancer/loadbalancer-service/src/test/java/com/huaweicloud/loadbalancer/YamlRuleConverterTest.java
  sermant-plugins/sermant-loadbalancer/spring-cloud-loadbalancer-plugin/src/main/java/com/huaweicloud/loadbalancer/cache/RibbonLoadbalancerCache.java
  sermant-plugins/sermant-loadbalancer/spring-cloud-loadbalancer-plugin/src/test/java/com/huaweicloud/loadbalancer/ClientFactoryInterceptorTest.java
  sermant-plugins/sermant-loadbalancer/spring-cloud-loadbalancer-plugin/src/test/java/com/huaweicloud/loadbalancer/LoadBalancerInterceptorTest.java
  sermant-plugins/sermant-loadbalancer/spring-cloud-loadbalancer-plugin/src/test/java/com/huaweicloud/loadbalancer/RibbonLoadBalancerInterceptorTest.java
  sermant-plugins/sermant-loadbalancer/spring-cloud-loadbalancer-plugin/src/test/java/com/huaweicloud/loadbalancer/RuleManagerHelper.java
  sermant-plugins/sermant-loadbalancer/spring-cloud-loadbalancer-plugin/src/test/java/com/huaweicloud/loadbalancer/cache/RibbonLoadbalancerCacheTest.java
Labels: document

#699 package add monitor module, fix arm can not get cpu cores.
  sermant-plugins/pom.xml
  sermant-plugins/sermant-monitor/monitor-service/src/main/java/com/huawei/monitor/command/CpuInfoCommand.java
Labels: bug

#705 【fix】整改sermant-agentcore-core UT
  sermant-agentcore/sermant-agentcore-core/src/test/java/com/huaweicloud/sermant/core/config/utils/ConfigValueUtilTest.java
  sermant-agentcore/sermant-agentcore-core/src/test/java/com/huaweicloud/sermant/core/service/dynamicconfig/BaseTest.java
  sermant-agentcore/sermant-agentcore-core/src/test/java/com/huaweicloud/sermant/core/service/dynamicconfig/KieDynamicConfigServiceTest.java
  sermant-agentcore/sermant-agentcore-core/src/test/java/com/huaweicloud/sermant/core/service/dynamicconfig/ZooKeeperDynamicConfigServiceTest.java
  sermant-agentcore/sermant-agentcore-core/src/test/java/com/huaweicloud/sermant/core/service/dynamicconfig/kie/PublishTest.java
  sermant-agentcore/sermant-agentcore-core/src/test/java/com/huaweicloud/sermant/core/service/monitor/MetricServiceTest.java
  sermant-plugins/sermant-dynamic-config/dynamic-config-plugin/src/test/java/com/huawei/dynamic/config/interceptors/SpringFactoriesInterceptorTest.java
Labels: area/core, area/test
