Repository sermant-io/Sermant, pull requests merged in 2023-11, with the labels that each got.

#1353 修复可以从插件类加载器中加载到宿主类的问题
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/plugin/classloader/PluginClassLoader.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/plugin/classloader/ServiceClassLoader.java
Labels: kind/bug, area/framework

#1351 流量标签透传插件集成测试部分demo和集成测试脚本
  .github/actions/common/plugin-change-check/action.yml
  .github/actions/common/tag-transmission/action.yml
  .github/actions/scenarios/tag-transmission/alibaba-dubbo/action.yml
  .github/actions/scenarios/tag-transmission/apache-dubbo/action.yml
  .github/actions/scenarios/tag-transmission/config/action.yml
  .github/actions/scenarios/tag-transmission/crossthread/action.yml
  .github/actions/scenarios/tag-transmission/grpc/action.yml
  .github/actions/scenarios/tag-transmission/httpclientv3/action.yml
  .github/actions/scenarios/tag-transmission/httpclientv4/action.yml
  .github/actions/scenarios/tag-transmission/jdkhttp-jetty/action.yml
  .github/actions/scenarios/tag-transmission/jdkhttp-tomcat/action.yml
  .github/actions/scenarios/tag-transmission/kafka/action.yml
  .github/actions/scenarios/tag-transmission/okhttp/action.yml
  .github/actions/scenarios/tag-transmission/rocketmq/action.yml
  .github/actions/scenarios/tag-transmission/servicecomb/action.yml
  .github/actions/scenarios/tag-transmission/sofarpc/action.yml
  .github/workflows/tagtransmission_integration_test.yml
  sermant-integration-tests/scripts/tryDownloadMidware.sh
  sermant-integration-tests/tag-transmission-test/kafka-consumer-demo/pom.xml
  sermant-integration-tests/tag-transmission-test/kafka-consumer-demo/src/main/java/com/huaweicloud/demo/tagtransmission/kafka/consumer/KafkaConsumerApplication.java
  sermant-integration-tests/tag-transmission-test/kafka-consumer-demo/src/main/java/com/huaweicloud/demo/tagtransmission/kafka/consumer/KafkaWithConsumer.java
  sermant-integration-tests/tag-transmission-test/kafka-consumer-demo/src/main/java/com/huaweicloud/demo/tagtransmission/kafka/consumer/controller/KafkaConsumerController.java
  sermant-integration-tests/tag-transmission-test/kafka-consumer-demo/src/main/resources/application.properties
  sermant-integration-tests/tag-transmission-test/kafka-producer-demo/pom.xml
  sermant-integration-tests/tag-transmission-test/kafka-producer-demo/src/main/java/com/huaweicloud/demo/tagtransmission/kafka/producer/KafkaProducerApplication.java
  sermant-integration-tests/tag-transmission-test/kafka-producer-demo/src/main/java/com/huaweicloud/demo/tagtransmission/kafka/producer/controller/KafkaProducerController.java
  sermant-integration-tests/tag-transmission-test/kafka-producer-demo/src/main/resources/application.properties
  sermant-integration-tests/tag-transmission-test/midware-common-demo/src/main/java/com/huaweicloud/demo/tagtransmission/midware/common/MessageConstant.java
  sermant-integration-tests/tag-transmission-test/rocketmq-consumer-demo/src/main/java/com/huaweicloud/demo/tagtransmission/rocketmq/consumer/RocketMqConsumer.java
  sermant-integration-tests/tag-transmission-test/rocketmq-producer-demo/pom.xml
  sermant-integration-tests/tag-transmission-test/rocketmq-producer-demo/src/main/java/com/huaweicloud/demo/tagtransmission/rocketmq/producer/RocketMqProducerApplication.java
  sermant-integration-tests/tag-transmission-test/rocketmq-producer-demo/src/main/java/com/huaweicloud/demo/tagtransmission/rocketmq/producer/controller/RocketMqProducerController.java
  sermant-integration-tests/tag-transmission-test/rocketmq-producer-demo/src/main/resources/application.properties
  sermant-integration-tests/tag-transmission-test/tag-transmission-integration-test/pom.xml
  sermant-integration-tests/tag-transmission-test/tag-transmission-integration-test/src/test/java/com/huaweicloud/demo/tagtransmission/integration/TagTransmissionTest.java
  sermant-integration-tests/tag-transmission-test/tag-transmission-integration-test/src/test/java/com/huaweicloud/demo/tagtransmission/integration/utils/RequestUtils.java
Labels: area/e2e-test

#1356 修复可以从插件类加载器中加载到宿主类的问题
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/plugin/classloader/PluginClassLoader.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/plugin/classloader/ServiceClassLoader.java
Labels: kind/bug, area/framework

#1355 获取sermant增强信息：插件、增强类、方法
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/AgentCoreEntrance.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/command/CheckEnhancementsCommandExecutor.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/command/Command.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/command/CommandProcessor.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/plugin/PluginManager.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/plugin/agent/info/EnhancementManager.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/plugin/agent/transformer/ReentrantTransformer.java
Labels: kind/feature, area/framework

#1363 readme文档更新
  README-en.md
  README.md
Labels: kind/enhancement, area/docs

#1364 1.2.x版本readme文档更新
  README-en.md
  README.md
Labels: kind/enhancement, area/docs

#1366 codecheck问题修改
  sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/java/com/huawei/flowcontrol/res4j/service/ServiceCollectorService.java
  sermant-plugins/sermant-monitor/monitor-service/src/main/java/com/huawei/monitor/service/collector/ServerCollectorService.java
  sermant-plugins/sermant-monitor/monitor-service/src/main/java/com/huawei/monitor/service/collector/ServiceCollectorService.java
  sermant-plugins/sermant-mq-consume-deny/message-common/src/main/java/com/huaweicloud/sermant/message/common/utils/MockUtils.java
  sermant-plugins/sermant-mq-consume-deny/rabbitmq-consumer-plugin/src/main/java/com/huaweicloud/sermant/rabbitmq/declarer/RabbitmqChannelDeclarer.java
  sermant-plugins/sermant-router/dubbo-router-service/src/main/java/com/huaweicloud/sermant/router/dubbo/handler/FlowRouteHandler.java
  sermant-plugins/sermant-router/router-common/src/main/java/com/huaweicloud/sermant/router/common/event/RouterEventCollector.java
  sermant-plugins/sermant-router/router-common/src/main/java/com/huaweicloud/sermant/router/common/event/RouterEventDefinition.java
  sermant-plugins/sermant-router/router-common/src/main/java/com/huaweicloud/sermant/router/common/utils/ReflectUtils.java
  sermant-plugins/sermant-router/router-config-common/src/main/java/com/huaweicloud/sermant/router/config/entity/RouterConfiguration.java
  sermant-plugins/sermant-router/router-config-common/src/main/java/com/huaweicloud/sermant/router/config/utils/PolicyEventUtils.java
  sermant-plugins/sermant-router/router-config-common/src/main/java/com/huaweicloud/sermant/router/config/utils/RuleUtils.java
  sermant-plugins/sermant-router/spring-router-plugin/src/main/java/com/huaweicloud/sermant/router/spring/handler/AbstractMappingHandler.java
  sermant-plugins/sermant-router/spring-router-plugin/src/main/java/com/huaweicloud/sermant/router/spring/handler/LaneRequestTagHandler.java
  sermant-plugins/sermant-router/spring-router-plugin/src/main/java/com/huaweicloud/sermant/router/spring/handler/RouteRequestTagHandler.java
  sermant-plugins/sermant-router/spring-router-plugin/src/main/java/com/huaweicloud/sermant/router/spring/interceptor/MarkInterceptor.java
  sermant-plugins/sermant-router/spring-router-service/src/main/java/com/huaweicloud/sermant/router/spring/handler/AbstractRouteHandler.java
  sermant-plugins/sermant-router/spring-router-service/src/main/java/com/huaweicloud/sermant/router/spring/handler/FlowRouteHandler.java
  sermant-plugins/sermant-service-registry/dubbo-registry-plugin/src/main/java/com/huawei/dubbo/registry/alibaba/NacosRegistryFactory.java
  sermant-plugins/sermant-service-registry/dubbo-registry-plugin/src/main/java/com/huawei/dubbo/registry/apache/NacosRegistryFactory.java
  sermant-plugins/sermant-service-registry/dubbo-registry-plugin/src/main/java/com/huawei/dubbo/registry/declarer/ApacheInterfaceConfigDeclarer.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/entity/InterfaceData.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/service/NacosRegistryServiceImpl.java
  sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/service/NacosServiceNotify.java
  sermant-plugins/sermant-service-registry/registry-common/src/main/java/com/huawei/registry/config/NacosRegisterConfig.java
  sermant-plugins/sermant-service-registry/registry-common/src/main/java/com/huawei/registry/config/grace/GraceHelper.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/auto/sc/ServiceCombServer.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/auto/sc/ServiceCombServiceInstance.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/config/RegisterDynamicConfig.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/config/RegistryConfigResolver.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/context/RegisterContext.java
Labels: kind/bug, area/plugin

#1367 codecheck问题修改
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/grace/interceptors/GraceSwitchInterceptor.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/grace/interceptors/SpringRibbonWarmUpInterceptor.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/grace/interceptors/SpringZuulResponseInterceptor.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/inject/OriginRegistrySwitchInjectDefine.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/inject/RibbonConfigurationDefine.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/inject/ScConfigurationInjectDefine.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/interceptors/RegistrationInterceptor.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/support/InstanceInterceptorSupport.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/support/RegisterSwitchSupport.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/utils/HostUtils.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-service/src/main/java/com/huawei/registry/service/cache/AddressCache.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-service/src/main/java/com/huawei/registry/service/client/NacosClient.java
  sermant-plugins/sermant-service-registry/spring-cloud-registry-service/src/main/java/com/huawei/registry/service/client/ScClient.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/cache/InstanceCache.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/interceptor/AbstractCallInterceptor.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/interceptor/AlibabaDubboInvokeInterceptor.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/interceptor/ApacheDubboInvokeInterceptor.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/interceptor/SpringBootApplyInterceptor.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/interceptor/SpringCloudClientInterceptor.java
  sermant-plugins/sermant-service-removal/removal-service/src/main/java/com/huaweicloud/sermant/event/RemovalEventDefinitions.java
  sermant-plugins/sermant-service-removal/removal-service/src/main/java/com/huaweicloud/sermant/service/RemovalEventServiceImpl.java
  sermant-plugins/sermant-springboot-registry/springboot-registry-plugin/src/main/java/com/huawei/discovery/config/LbConfig.java
  sermant-plugins/sermant-springboot-registry/springboot-registry-plugin/src/main/java/com/huawei/discovery/event/SpringBootRegistryEventDefinition.java
  sermant-plugins/sermant-springboot-registry/springboot-registry-plugin/src/main/java/com/huawei/discovery/interceptors/FeignInvokeInterceptor.java
  sermant-plugins/sermant-springboot-registry/springboot-registry-plugin/src/main/java/com/huawei/discovery/interceptors/HttpComponentsClientHttpConnectorInterceptor.java
  sermant-plugins/sermant-springboot-registry/springboot-registry-plugin/src/main/java/com/huawei/discovery/interceptors/JettyRequestInterceptor.java
  sermant-plugins/sermant-springboot-registry/springboot-registry-plugin/src/main/java/com/huawei/discovery/interceptors/MarkInterceptor.java
  sermant-plugins/sermant-springboot-registry/springboot-registry-plugin/src/main/java/com/huawei/discovery/interceptors/MonoHttpConnectInterceptor.java
  sermant-plugins/sermant-springboot-registry/springboot-registry-plugin/src/main/java/com/huawei/discovery/interceptors/OkHttp3ClientInterceptor.java
  sermant-plugins/sermant-springboot-registry/springboot-registry-plugin/src/main/java/com/huawei/discovery/interceptors/OkHttpClientInterceptor.java
  sermant-plugins/sermant-springboot-registry/springboot-registry-plugin/src/main/java/com/huawei/discovery/interceptors/RestTemplateInterceptor.java
  sermant-plugins/sermant-springboot-registry/springboot-registry-plugin/src/main/java/com/huawei/discovery/interceptors/httpclient/HttpAsyncClient4xInterceptor.java
  sermant-plugins/sermant-springboot-registry/springboot-registry-plugin/src/main/java/com/huawei/discovery/interceptors/httpclient/HttpClient4xInterceptor.java
  sermant-plugins/sermant-springboot-registry/springboot-registry-plugin/src/main/java/com/huawei/discovery/interceptors/httpconnection/HttpUrlConnectionConnectInterceptor.java
  sermant-plugins/sermant-springboot-registry/springboot-registry-plugin/src/main/java/com/huawei/discovery/retry/DefaultRetryImpl.java
  sermant-plugins/sermant-springboot-registry/springboot-registry-plugin/src/main/java/com/huawei/discovery/retry/Retry.java
  sermant-plugins/sermant-springboot-registry/springboot-registry-plugin/src/main/java/com/huawei/discovery/utils/HttpConstants.java
  sermant-plugins/sermant-springboot-registry/springboot-registry-plugin/src/main/java/com/huawei/discovery/utils/PlugEffectWhiteBlackUtils.java
  sermant-plugins/sermant-springboot-registry/springboot-registry-plugin/src/test/java/com/huawei/discovery/interceptors/MarkInterceptorTest.java
  sermant-plugins/sermant-springboot-registry/springboot-registry-service/src/main/java/com/huawei/discovery/service/lb/discovery/zk/ZkServiceManager.java
  sermant-plugins/sermant-springboot-registry/springboot-registry-service/src/main/java/com/huawei/discovery/service/lb/discovery/zk/listen/ZkInstanceListenable.java
  sermant-plugins/sermant-springboot-registry/springboot-registry-service/src/main/java/com/huawei/discovery/service/lb/stats/InstanceStats.java
  sermant-plugins/sermant-springboot-registry/springboot-registry-service/src/main/java/com/huawei/discovery/service/registry/RegistryImpl.java
  sermant-plugins/sermant-springboot-registry/springboot-registry-service/src/main/java/com/huawei/discovery/service/retry/RetryServiceImpl.java
  sermant-plugins/sermant-springboot-registry/springboot-registry-service/src/main/java/com/huawei/discovery/service/util/ApplyUtil.java
Labels: kind/enhancement, area/framework, area/plugin
