Repository sermant-io/Sermant, pull requests merged in 2023-04, with the labels that each got.

#1163 【enhancement】优化输出被增强类字节码文件的开关和路径配置
  sermant-agentcore/sermant-agentcore-config/config/config.properties
  sermant-agentcore/sermant-agentcore-config/config/test/config.properties
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/common/CommonConstant.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/plugin/agent/BufferedAgentBuilder.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/plugin/agent/config/AgentConfig.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/utils/FileUtils.java
Labels: kind/enhancement, lgtm

#1167 【bug】修改离群实例插件的事件上报描述以及流控插件的漏洞
  sermant-plugins/sermant-flowcontrol/flowcontrol-service/pom.xml
  sermant-plugins/sermant-service-removal/removal-service/src/main/java/com/huaweicloud/sermant/event/RemovalEventDefinitions.java
  sermant-plugins/sermant-service-removal/removal-service/src/main/java/com/huaweicloud/sermant/service/RemovalEventServiceImpl.java
Labels: kind/bug, lgtm

#1165 【enhancement】将服务黑名单开关服务改为统一通过开关配置
  sermant-agentcore/sermant-agentcore-config/config/config.properties
  sermant-agentcore/sermant-agentcore-config/config/test/config.properties
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/event/config/EventConfig.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/plugin/agent/config/AgentConfig.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/service/ServiceConfig.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/service/ServiceManager.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/service/send/config/GatewayConfig.java
  sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/service/visibility/config/VisibilityServiceConfig.java
  sermant-agentcore/sermant-agentcore-core/src/main/resources/META-INF/services/com.huaweicloud.sermant.core.config.common.BaseConfig
  sermant-agentcore/sermant-agentcore-implement/src/main/java/com/huaweicloud/sermant/implement/service/heartbeat/HeartbeatServiceImpl.java
  sermant-agentcore/sermant-agentcore-implement/src/main/java/com/huaweicloud/sermant/implement/service/send/netty/NettyClient.java
  sermant-agentcore/sermant-agentcore-implement/src/main/java/com/huaweicloud/sermant/implement/service/send/netty/NettyClientFactory.java
  sermant-agentcore/sermant-agentcore-implement/src/main/java/com/huaweicloud/sermant/implement/service/send/netty/NettyGatewayClient.java
  sermant-agentcore/sermant-agentcore-implement/src/main/java/com/huaweicloud/sermant/implement/service/visibility/VisibilityServiceImpl.java
Labels: kind/enhancement, lgtm

#1174 【bugfix】修改服务可见性消息的类型值
  .github/actions/common/plugin-change-check/action.yml
  sermant-plugins/sermant-service-visibility/service-visibility-service/src/main/java/com/huaweicloud/visibility/service/CollectorServiceImpl.java
Labels: kind/bug, lgtm

#1172 事件同名字段计数优化
  sermant-backend/src/main/java/com/huaweicloud/sermant/backend/common/conf/BackendConfig.java
  sermant-backend/src/main/java/com/huaweicloud/sermant/backend/dao/memory/MemoryClientImpl.java
  sermant-backend/src/main/java/com/huaweicloud/sermant/backend/dao/redis/RedisClientImpl.java
  sermant-backend/src/main/java/com/huaweicloud/sermant/backend/server/NettyServer.java
  sermant-backend/src/main/resources/application.properties
Labels: kind/enhancement, lgtm

#1178 【enhancement】http请求兼容非标准HttpMethod的实现
  sermant-plugins/sermant-springboot-registry/springboot-registry-plugin/src/main/java/com/huawei/discovery/interceptors/httpclient/HttpClient4xInterceptor.java
Labels: kind/enhancement, lgtm

#1179 【enhancement】http请求兼容非标准HttpMethod的实现（1.0.x）
  sermant-plugins/sermant-springboot-registry/springboot-registry-plugin/src/main/java/com/huawei/discovery/interceptors/httpclient/HttpClient4xInterceptor.java
Labels: kind/enhancement, lgtm

#1180 【enhancement】http请求兼容非标准HttpMethod的实现（develop）
  sermant-plugins/sermant-springboot-registry/springboot-registry-plugin/src/main/java/com/huawei/discovery/interceptors/httpclient/HttpClient4xInterceptor.java
Labels: kind/enhancement, lgtm

#1183 【bug】修改离群实例摘除插件的review意见
  sermant-plugins/sermant-service-removal/config/config.yaml
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/cache/DubboCache.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/cache/InstanceCache.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/cache/RuleCache.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/common/RemovalConstants.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/config/RemovalConfig.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/config/RemovalRule.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/declarer/AbstractSwitchDeclarer.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/declarer/AlibabaDubboClusterUtilsDeclarer.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/declarer/AlibabaDubboDirectoryDeclarer.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/declarer/AlibabaDubboInvokeDeclarer.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/declarer/ApacheDubboClusterUtilsDeclarer.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/declarer/ApacheDubboDirectoryDeclarer.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/declarer/ApacheDubboMonitorDeclarer.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/declarer/SpringBootApplyDeclarer.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/declarer/SpringBootCacheManagerDeclarer.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/declarer/SpringCloudClientDeclarer.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/declarer/SpringCloudDiscoveryDeclarer.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/declarer/SpringCloudLoadBalancerClientDeclarer.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/declarer/SpringCloudReactiveDiscoveryDeclarer.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/declarer/SpringCloudServerListDeclarer.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/entity/InstanceInfo.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/entity/RequestInfo.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/interceptor/AbstractCallInterceptor.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/interceptor/AbstractClusterUtilsInterceptor.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/interceptor/AbstractRemovalInterceptor.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/interceptor/AbstractSwitchInterceptor.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/interceptor/AlibabaDubboClusterUtilsInterceptor.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/interceptor/AlibabaDubboDirectoryInterceptor.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/interceptor/ApacheDubboClusterUtilsInterceptor.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/interceptor/ApacheDubboDirectoryInterceptor.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/interceptor/SpringBootApplyInterceptor.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/interceptor/SpringBootCacheManagerInterceptor.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/interceptor/SpringCloudDiscoveryInterceptor.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/interceptor/SpringCloudReactiveDiscoveryInterceptor.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/main/java/com/huaweicloud/sermant/interceptor/SpringCloudServerListInterceptor.java
  sermant-plugins/sermant-service-removal/removal-plugin/src/test/java/com/huaweicloud/sermant/cache/InstanceCacheTest.java
  sermant-plugins/sermant-service-removal/removal-service/pom.xml
  sermant-plugins/sermant-service-removal/removal-service/src/main/java/com/huaweicloud/sermant/config/RemovalDynamicConfigListener.java
  sermant-plugins/sermant-service-removal/removal-service/src/main/java/com/huaweicloud/sermant/service/RemovalConfigService.java
  sermant-plugins/sermant-service-removal/removal-service/src/main/java/com/huaweicloud/sermant/service/RemovalEventServiceImpl.java
  sermant-plugins/sermant-service-removal/removal-service/src/main/java/com/huaweicloud/sermant/service/RequestDataCountTask.java
  sermant-plugins/sermant-service-removal/removal-service/src/main/resources/META-INF/services/com.huaweicloud.sermant.core.plugin.service.PluginService
  sermant-plugins/sermant-service-removal/removal-service/src/test/java/com/huaweicloud/sermant/service/RequestDataCountTaskTest.java
Labels: kind/bug, lgtm

#1184 离群实例摘除插件更新监听group路径
  sermant-plugins/sermant-service-removal/removal-service/src/main/java/com/huaweicloud/sermant/service/RemovalConfigService.java
Labels: kind/bug, lgtm

#1185 修改事件过期时间单位和webhook通知级别
  sermant-backend/src/main/java/com/huaweicloud/sermant/backend/dao/memory/MemoryClientImpl.java
  sermant-backend/src/main/java/com/huaweicloud/sermant/backend/dao/redis/RedisClientImpl.java
  sermant-backend/src/main/resources/application.properties
Labels: kind/enhancement, lgtm

#1202 【fix】修复springboot注册插件获取spring.application.name的bug
  pom.xml
  sermant-backend/pom.xml
  sermant-plugins/sermant-springboot-registry/springboot-registry-plugin/src/main/java/com/huawei/discovery/declarers/SpringEnvironmentInfoDeclarer.java
  sermant-plugins/sermant-springboot-registry/springboot-registry-plugin/src/main/java/com/huawei/discovery/entity/DefaultServiceInstance.java
  sermant-plugins/sermant-springboot-registry/springboot-registry-plugin/src/main/java/com/huawei/discovery/interceptors/SpringEnvironmentInfoInterceptor.java
  sermant-plugins/sermant-springboot-registry/springboot-registry-plugin/src/test/java/com/huawei/discovery/interceptors/SpringEnvironmentInfoInterceptorTest.java
Labels: kind/bug, area/plugin

#1204 【fix】修复springboot注册插件获取spring.application.name的bug
  pom.xml
  sermant-backend/pom.xml
  sermant-plugins/sermant-springboot-registry/springboot-registry-plugin/src/main/java/com/huawei/discovery/declarers/SpringEnvironmentInfoDeclarer.java
  sermant-plugins/sermant-springboot-registry/springboot-registry-plugin/src/main/java/com/huawei/discovery/entity/DefaultServiceInstance.java
  sermant-plugins/sermant-springboot-registry/springboot-registry-plugin/src/main/java/com/huawei/discovery/interceptors/SpringEnvironmentInfoInterceptor.java
  sermant-plugins/sermant-springboot-registry/springboot-registry-plugin/src/test/java/com/huawei/discovery/interceptors/SpringEnvironmentInfoInterceptorTest.java
Labels: kind/bug, area/plugin
